feat: add oidc authentication support [WD-11658]
canonical/microcloud-cluster-manager pull request #11
Opened 2024-06-04 12:59 UTC by mas-who

## Done

- [x] Copied over oidc package from lxd (including latest zitadel v3 update)
- [x] Setup global state for site manager and pass to all endpoint handlers
- [x] Setup oidc endpoints for site manager (`/oidc/login`, `/oidc/callback`, `/oidc/logout`)
- [x] Removed what's not needed for site manager from oidc package
- [x] Implemented authentication check on protected api endpoints
- [x] Added UI login tests
- [x] Adjusted demo server setup for oidc authentication

2024-06-06 14:25 UTC, markylaing commented on auth/auth.go
> +	userInfo, err := rp.Userinfo(accessToken, oidc.BearerToken, claims.Subject, o.relyingParty)
One of the reasons LXD needs to cache identities is so that the email address of a user that logs in via a bearer token can be found without this call. The OIDC library will make a HTTP request here to the IdP to get user information on every request.

2024-06-06 14:28 UTC, markylaing commented on auth/auth.go
> +		fmt.Printf("SecureCookie: %v\n", secureCookie)
Looks like some debug logging?

2024-06-06 14:32 UTC, markylaing commented on auth/auth.go
> +}
These headers written to the response when OIDC authentication fails. The CLI uses them to perform a device login flow in it's end and get an access token. You could use a similar approach, but I'd recommend changing the headers themselves e.g. `X-LXD-OIDC-issuer` -> `X-LXD-site-manager-OIDC-issuer`.

2024-06-06 14:57 UTC, markylaing commented on cmd/lxd-site-mgrd/main.go
> +		api.OidcLogoutCmd(oidcVerifier),
When changing OIDC configuration, you will likely need access to the `oidcVerifier` in scope of a handler. It might be a good idea to have your own state type, similar to the microcluster state which has the `oidcVerifier` as a field, then pass that as an argument when instantiating your handler funcs.

2024-06-06 15:35 UTC, markylaing commented on auth/auth.go
> +	callbackURL := fmt.Sprintf("%s://%s/1.0/oidc/callback", proto, host)
I'm not sure what the best approach is here. This is a good idea, but IIRC I've also had this working with [sticky sessions](https://www.haproxy.com/blog/enable-sticky-sessions-in-haproxy). We'll have to have a think about the behaviour of LXD when behind a load balancer and perhaps we can come to a general solution.

2024-06-06 15:39 UTC, markylaing commented on auth/auth.go
> +	host := getHeaderOrDefault(r, "X-Forwarded-Host", r.Host)
Generally for code style we like to have a newline after each code block or each logical set of calls.

2024-06-06 16:01 UTC, markylaing commented
Last comment for now is more about repo structure. Golang codebases now tend to follow [this convention](https://github.com/golang-standards/project-layout?tab=readme-ov-file#go-directories). Many of our repos don't follow this convention, I'm not certain as to the reasons for this, but it's good practise to try and follow. 

Since you don't want other go programs to import any of this codebase yet, I would initially create an `internal` directory and then move your `auth` and `api` packages into it :)

2024-06-07 07:24 UTC, mas-who commented on auth/auth.go
> +	userInfo, err := rp.Userinfo(accessToken, oidc.BearerToken, claims.Subject, o.relyingParty)
I see, this is referring to the [identityCache](https://github.com/canonical/lxd/blob/9387ded1aee7888f37dd1a8714cada3f7ad31d7e/lxd/auth/oidc/oidc.go#L150) right? From what I can see, the `identityCache` is coupled to some local concepts in LXD. Am I correct to say that in site manager we only need the `Identifier`, `Name` and `Subject` fields from the `identity.CacheEntry` struct? I wonder if we should import the identity package as a dependency in site manager to reuse the existing cache structure, not sure if it will work since site manager does not have tls authentication and also we won't be implementing fine grained authorisation yet. Maybe we can setup a site manager version of the cache wdyt?

2024-06-07 07:29 UTC, mas-who commented on auth/auth.go
> +}
We are not planning to implement oidc for CLI in site manager. I was actually going to ask how auth validation works in LXD once the user authenticates. Based on what you said, does that mean we should also implement oidc for CLI if we want to leverage what LXD has for auth validation?

2024-06-07 07:31 UTC, mas-who commented on cmd/lxd-site-mgrd/main.go
> +		api.OidcLogoutCmd(oidcVerifier),
Thanks will do that :slightly_smiling_face:

2024-06-07 07:32 UTC, mas-who commented on auth/auth.go
> +	callbackURL := fmt.Sprintf("%s://%s/1.0/oidc/callback", proto, host)
Will look into sticky sessions. I think there is a wider discussion here as well. Are we happy with progressing to make relevant changes in the site manager version of the oidc package for now, get a sense of the requirement then later look into generalising the oidc package in lxd?

2024-06-07 07:37 UTC, mas-who commented on auth/auth.go
> +	host := getHeaderOrDefault(r, "X-Forwarded-Host", r.Host)
aah right, the thinking here is that the logical set of calls is for constructing the callback url, I think putting this block into a function might improve readability?

2024-06-07 07:38 UTC, mas-who commented
> Last comment for now is more about repo structure. Golang codebases now tend to follow [this convention](https://github.com/golang-standards/project-layout?tab=readme-ov-file#go-directories). Many of our repos don't follow this convention, I'm not certain as to the reasons for this, but it's good practise to try and follow.
> 
> Since you don't want other go programs to import any of this codebase yet, I would initially create an `internal` directory and then move your `auth` and `api` packages into it :)

This is great! :smile: will make a separate PR to readjusted the codebase structure

2024-06-07 07:39 UTC, tomponline commented
> > Last comment for now is more about repo structure. Golang codebases now tend to follow [this convention](https://github.com/golang-standards/project-layout?tab=readme-ov-file#go-directories). Many of our repos don't follow this convention, I'm not certain as to the reasons for this, but it's good practise to try and follow.
> > Since you don't want other go programs to import any of this codebase yet, I would initially create an `internal` directory and then move your `auth` and `api` packages into it :)
> 
> This is great! 😄 will make a separate PR to readjusted the codebase structure

Yes please make good use of `internal` to avoid becoming an unexpected dependency elsewhere.

2024-06-25 11:50 UTC, edlerd requested changes

2024-06-25 11:50 UTC, edlerd commented on .gitignore
> +!internal/state
```suggestion
internal/state
```
Typo?

2024-06-25 11:50 UTC, edlerd commented on ui/haproxy.cfg
> +  use_backend go_backend if is_backend !is_ui
```suggestion
  use_backend go_backend if is_backend
```
Can simplify here.

2024-06-25 11:50 UTC, edlerd commented on internal/api/api.go
> +type endpointHandlerWithState func(*state.SiteManagerState, *microclusterState.State, http.ResponseWriter, *http.Request) response.Response
```suggestion
```
I don't think we need this.

2024-06-25 11:50 UTC, edlerd commented on internal/api/api.go
> +			return handler(s, innerState, w, r).Render(w)
```suggestion
			return handler(innerState, r).Render(w)
```
The other two params are not needed in the handlers.

2024-06-25 11:50 UTC, edlerd commented on internal/api/sites.go
> +func sitesGet(s *state.SiteManagerState, innerState *microclusterState.State, w http.ResponseWriter, r *http.Request) response.Response {
```suggestion
func sitesGet(innerState *microclusterState.State, r *http.Request) response.Response {
```
Can this be removed?

2024-06-25 11:50 UTC, edlerd commented on internal/api/sites.go
> +func sitesGet(s *state.SiteManagerState, innerState *microclusterState.State, w http.ResponseWriter, r *http.Request) response.Response {
Also in the siteget below.

2024-06-26 06:07 UTC, mas-who commented on auth/auth.go
> +	userInfo, err := rp.Userinfo(accessToken, oidc.BearerToken, claims.Subject, o.relyingParty)
Since we would be using access token verification currently in site manager, `identityCache` isn't really needed. Although I did setup a simpler version of `identityCache` here to mimic the same flow in lxd, not sure if I should remove this rather?

2024-06-26 06:15 UTC, mas-who commented on internal/api/api.go
> +type endpointHandlerWithState func(*state.SiteManagerState, *microclusterState.State, http.ResponseWriter, *http.Request) response.Response
As discussed, we will keep the interface simple for now :slightly_smiling_face:

2024-06-26 08:52 UTC, mas-who commented
@edlerd  I've added e2e tests for login/logout as well. It requires use of repository secrets though so CI will fail on a forked PR before this is merged. Also I don't have access to Settings in this repo. Here is a success [action run](https://github.com/mas-who/lxd-site-manager/actions/runs/9676264964) for the login e2e tests on my fork.

2024-06-26 10:23 UTC, edlerd commented on .github/workflows/pr.yaml
> +
```suggestion

```

2024-06-26 10:23 UTC, edlerd commented on internal/api/sites.go
> +func sitesGet(innerState *microclusterState.State, r *http.Request) response.Response {
```suggestion
func sitesGet(s *microclusterState.State, r *http.Request) response.Response {
```
Keep naming simple? Also relevant below.

2024-06-26 10:23 UTC, edlerd commented on internal/api/types/rest.go
> +type EndpointHandler func(*state.State, *http.Request) response.Response
Should this type be upstreamed to microcluster?

2024-06-26 10:23 UTC, edlerd commented on ui/haproxy.cfg
> +  bind BIND_ADDRESS ssl verify optional crt keys/lxd-sm.pem ca-file keys/lxd-sm.crt
The bind should be the first line, so the config list the ingress first and the egress last. In between, we have handling of the request.

2024-06-26 13:33 UTC, mas-who commented on internal/api/types/rest.go
> +type EndpointHandler func(*state.State, *http.Request) response.Response
Yes we should add it to this [file](https://github.com/canonical/microcluster/blob/main/rest/rest.go) in microcluster. Will create an issue for it.

2024-06-26 13:38 UTC, mas-who commented on ui/haproxy.cfg
> +  bind BIND_ADDRESS ssl verify optional crt keys/lxd-sm.pem ca-file keys/lxd-sm.crt
yeah that makes sense :+1:

2024-06-26 17:20 UTC, edlerd approved these changes
LGTM :+1:

2024-06-27 09:25 UTC, mas-who commented on auth/auth.go
> +	callbackURL := fmt.Sprintf("%s://%s/1.0/oidc/callback", proto, host)
As per previous discussions, we will look into forwarding requests to the correct host for this.

2024-06-27 09:26 UTC, mas-who commented on auth/auth.go
> +}
As per previous discussion, we do not need these headers in site manager for now since we are not implementing authentication for the CLI. Will keep these headers for now in case if we need to implement device grant flow later.

2024-06-27 11:50 UTC, edlerd approved these changes

2024-06-28 11:46 UTC, mas-who commented
@edlerd @markylaing the latest commit implements forwarding idp callback request to the member that initiated the login flow, please have a look when you get some time. 

FYI: There is a bug in microcluster at the moment which will cause CI to fail. I have a [PR](https://github.com/canonical/microcluster/pull/163) open to fix it.

Edit: Fix was merged so CI should pass now.

2024-06-28 16:26 UTC, markylaing reviewed
I've left some general feedback and comments. For the commit which will allow forwarding for the OIDC callback to the correct member, I think it's best if we have a call to discuss :)

2024-06-28 16:26 UTC, markylaing commented on .gitignore
> +!internal/state
I'm finding this commit a bit confusing. What does it have to do with OIDC? Should it be in a separate PR to be merged first?

This particular line is also a bit confusing to me. Why was `state` ignored to begin with?

2024-06-28 16:26 UTC, markylaing commented on internal/oidc/oidc.go
> +	"github.com/canonical/lxd/shared/api"
I don't think these imports should have moved. Imports should be in three blocks:
1. Go stdlib imports.
2. External non-stdlib dependencies.
3. In-project package dependencies.

Each block should be in alphabetical order. The `gci` linter should catch this.

2024-06-28 16:26 UTC, markylaing commented on internal/identity/cache.go
> +// Get returns a single CacheEntry by its authentication method and identifier.
The comment is out of date now.

2024-06-28 16:26 UTC, markylaing commented on internal/identity/cache.go
> +	IdentityType string
Do we need `IdentityType` if they are all OIDC identities?

2024-06-28 16:26 UTC, markylaing commented on internal/oidc/oidc.go
> +	"github.com/canonical/lxd/shared/api"
These have moved around a few times between commits.

2024-06-28 16:26 UTC, markylaing commented on internal/oidc/oidc.go
> +	"github.com/canonical/lxd-site-manager/internal/identity"
As this import is in the same module it should be in the last block.

2024-06-28 16:26 UTC, markylaing commented on cmd/lxd-site-mgrd/main.go
> +		func() *shared.CertInfo { return &shared.CertInfo{} },
Why is this returning an empty certificate? I think this needs to be the cluster certificate.

2024-06-28 16:26 UTC, markylaing commented on internal/oidc/oidc.go
> +)
As you have said, these should be removed. Can you get these from a environment variables for now?

2024-06-28 16:26 UTC, markylaing commented on cmd/lxd-site-mgrd/main.go
> +		func() *shared.CertInfo { return &shared.CertInfo{} },
Never mind, I see in the next commit that the cluster cert is being set on a microcluster hook. Perhaps the verifier can be set then as well?

2024-06-28 16:26 UTC, markylaing commented on internal/oidc/oidc.go
> +		http.Redirect(w, r, "/ui", http.StatusMovedPermanently)
Is this related to OIDC?

2024-06-28 16:26 UTC, markylaing commented on ui/entrypoint
> +fi
I think LXD has some utils for generating certificates that match what it generates by default if that is of interest? https://github.com/canonical/lxd/blob/762f7dc5c3dc4dbd0863a796898212d8fbe3f7c3/test/includes/certificates.sh

Also if this is for development, do you need the certificate to be valid for 3000 days?

2024-06-28 16:26 UTC, markylaing commented on internal/oidc/oidc.go
> +func getHeaderOrDefault(r *http.Request, headerName string, defaultValue string) string {
Now that the member address is encoded in the OIDC state, do you need these functions for getting headers? Also, do they rely upon the correct configuration of the external load balancer?

2024-06-28 16:26 UTC, markylaing commented on internal/api/api.go
> +		if s.OidcVerifier.IsRequest(r) {
Since only OIDC is allowed, I would reverse this if statement. E.g.:
```golang
if !s.OidcVerifier.IsRequest(r) {
    return response.Forbidden(nil)
}

// Rest of OIDC logic ...
```

2024-06-28 16:26 UTC, markylaing commented on internal/api/api.go
> +		if s.OidcVerifier == nil {
Also since OIDC is an acronym should we rename this to `OIDCVerifier`?

2024-06-28 16:26 UTC, markylaing commented on internal/api/api.go
> +		}
I just want to check I'm following this logic correctly.

- If there is an error when getting the identity from the cache by their email address, and that error is not a 404 Not Found error, return a 403 Forbidden. Should this be a 500 internal error? Or some other error more reflective of what occurred inside the identity cache?
- Otherwise, if there was a 404 Not Found error, or if the identity we found in the cache is different from the identity that authenticated, then replace all identities in the cache with the current one. What happens when more than one identity authenticates? Also, will propagating this to other members be added in a subsequent PR?

2024-06-28 16:26 UTC, markylaing commented on internal/api/api.go
> +			result, err := s.OidcVerifier.Auth(innerState.Context, authCtx, r)
Why do you need pass an `oidc.AuthCtx` into the `Auth` function? Can this be set in the request context instead?

2024-06-28 16:26 UTC, markylaing commented on internal/api/api.go
> +		return response.ManualResponse(func(w http.ResponseWriter) error {
Would it be possible to pass a `http.ResponseWriter` into `(oidc.OidcVerifier).Auth` so that we can write/delete cookies as necessary? Otherwise this is splitting auth logic into lots of different places and will become hard to keep track of I think.

2024-06-28 16:26 UTC, markylaing commented on ui/vite.config.ts
> +        target: "https://0.0.0.0:8414/",
Is this for development purposes? I'm not sure what it has to do with the commit message?

2024-06-28 16:26 UTC, markylaing commented on internal/oidc/context.go
> +type authCtxKey string
Generally I'm not sure about moving this logic outside of the authorizer itself.

Why can't the authorizer accept a `http.ResponseWriter` argument? Is this because you would need to wrap it in a `response.Manual` response? I guess that complicates matters...

2024-06-28 16:26 UTC, markylaing commented on internal/oidc/oidc.go
> +		proto = "https"
The protocol should always be `https` shouldn't it? IIRC microcluster doesn't have any non-TLS listeners?

2024-06-28 16:26 UTC, markylaing commented on internal/api/auth.go
> +	"context"
There's quite a lot going on in this commit and it's my EOD so I'll come back to this on Monday. Perhaps we can have a call to discuss :)

2024-07-01 07:36 UTC, mas-who commented on .gitignore
> +!internal/state
`state` is the state directory for the cluster so we want to ignore it. The directory `internal/state` holds the package for the site manager state definition which we want to track changes. Thanks for pointing this out though, I see there is a better way to do this. To ignore only the top level `state` directory, we just need to change `state` to `/state/` in `.gitignore`

2024-07-01 07:38 UTC, mas-who commented on internal/oidc/oidc.go
> +	"github.com/canonical/lxd/shared/api"
Thanks, I will have a look across the commits and clean it up :+1: 

Edit: the reason why the imports moved between commits is because I ran the gci linter in later commits than the one that introduced the dependencies, will avoid this moving forward (note to self)

2024-07-01 08:00 UTC, mas-who commented on internal/identity/cache.go
> +	IdentityType string
Yes nice catch, `IdentityType` is not relevant in site maanger :+1: will remove it

2024-07-01 08:01 UTC, mas-who commented on internal/oidc/oidc.go
> +	"github.com/canonical/lxd/shared/api"
I've cleaned up the commits so that the dependencies are correctly imported in the oidc package in the first commit

2024-07-01 08:21 UTC, mas-who commented on cmd/lxd-site-mgrd/main.go
> +		func() *shared.CertInfo { return &shared.CertInfo{} },
Nice yeah if it's much simpler to just set the verifier in the `OnStart` hook. I've also squashed the commits since there is no need to create an additional `SetClusterCertificate` method in the oidc package.

2024-07-01 08:27 UTC, mas-who commented on internal/oidc/oidc.go
> +		http.Redirect(w, r, "/ui", http.StatusMovedPermanently)
No, I've updated the commit message :+1:

2024-07-01 08:33 UTC, mas-who commented on internal/oidc/oidc.go
> +func getHeaderOrDefault(r *http.Request, headerName string, defaultValue string) string {
No I actually removed this in the second last commit. There is no requirements for the external load balancer now. Previously I needed the `X-FORWARDED` headers in the haproxy due to an incorrect configuration, will explain in the call.

2024-07-01 08:55 UTC, mas-who commented on ui/vite.config.ts
> +        target: "https://0.0.0.0:8414/",
Nice catch, I've moved it to the next commit which is for adding UI tests

2024-07-01 10:43 UTC, mas-who commented on internal/api/api.go
> +		}
Thanks for catching these, I've made the following changes:
 - Return internal error if we end up with an error that is not `404 Not Found` when fetching from the cache
 - Created a `(identity.Cache).ReplaceOrCreate` method which would simply just overwrite a cached identity by its identifier key in the cache or create an entry if the identifier does not exist.
 - I am planning on propagating the identity cache changes at a later stage, especially for when we have oidc configs stored in the database.

2024-07-01 10:58 UTC, mas-who commented on internal/oidc/oidc.go
> +)
My immediate next task is to create the `/config` endpoint and these settings will be stored in the configs table and these constant variables will be removed. For now, I think we can keep it here since it affects CICD workflows and I don't really want to set up everything based on environment variables knowing that later I will update the workflow anyway. wdyt?

2024-07-01 11:20 UTC, mas-who commented on internal/api/api.go
> +			result, err := s.OidcVerifier.Auth(innerState.Context, authCtx, r)
I have moved the removed the `AuthCtx` argument from all oidc functions.

2024-07-01 11:33 UTC, mas-who commented on internal/oidc/oidc.go
> +		proto = "https"
yes I've made it so that the callback url will always have the `https` protocol

2024-07-01 12:00 UTC, mas-who commented on internal/api/auth.go
> +	"context"
As discussed, I've made the following changes
- Removed source host from the forwarded callback request payload
- Created two functions, `handleCallback` and `handleForwardedCallback`. If the request is a cluster notification, process the request with `handleForwardedCallback`.
- Found a way to use the exact cluster member client using `(microcluster.Microcluster).RemoteClient`

2024-07-01 17:14 UTC, mas-who commented on ui/entrypoint
> +fi
Aah yes for development we use the cert for haproxy which the browser will communicate with, we don't really want to replace the cert during development.

2024-07-02 18:47 UTC, mas-who commented on internal/api/api.go
> +		return response.ManualResponse(func(w http.ResponseWriter) error {
With the upstream [PR](https://github.com/canonical/microcluster/pull/164) merged, I have adjusted so that `(oidc.OIDCVerifier).Auth` returns a `response.Response` if we need to modify the response.

2024-07-02 18:48 UTC, mas-who commented on internal/oidc/context.go
> +type authCtxKey string
This file is now completely removed.

2024-07-04 09:45 UTC, markylaing commented on .gitignore
> +!internal/state
I'm not following here. Do you mean `{repo_root}/state` is being used for local development?

We use `TEST_DIR=$(mktemp -d -p "$(pwd)" tmp.XXX)` when testing and ignore all files/folders prefixed with `tmp` in the repo. I think that this makes things a bit clearer but it's up to you.

2024-07-04 09:45 UTC, edlerd commented on internal/oidc/oidc.go
> +)
Let's merge the config endpoints first, so we can rely on them here and not commit the hard coded values.

2024-07-04 09:55 UTC, markylaing commented on internal/oidc/oidc.go
> +)
Ok sounds good.

2024-07-04 10:04 UTC, mas-who commented on internal/api/api.go
> +		}
remove the identity cache since it's not needed here.

2024-07-04 10:27 UTC, mas-who commented on internal/client/auth.go
> +	targetURL := api.NewURL().Path("oidc/callback")
Path("oidc", "callback")

2024-07-04 10:37 UTC, mas-who commented on internal/api/auth.go
> +	"context"
Create issues in microcluster and site manager to detail reasons why we have some weird code. We should also comment a bunch referencing the issues.

2024-07-04 10:43 UTC, markylaing commented on internal/api/types/rest.go
> +type EndpointHandler func(*state.State, *http.Request) response.Response
@masnax @roosterfish Should we define these types in microcluster?

2024-07-04 19:45 UTC, mas-who commented
@markylaing as discussed, I've done the following:
 - cleaned up commits to not have conflicting changes. Also cherry picked some commits and created #35 which should be merged before this PR.
 - removed the hard coded oidc configs. Now the oidc settings will be set by the `/1.0/config` endpoint, and updates will be propagated to all running cluster members. When a new member joins, we will get the oidc settings from dqlite and set it on the new member daemon.
 - removed the identity cache previously defined in this project since it's not needed.
 - added comments highlighting issues relating to not being able to construct the request efficiently for forwarding due to microcluster restrictions. I will create the GH issues once this PR is merged.
 - I decided to keep the e2e test commit in this PR. Since enabling oidc access handler on some endpoints will result in the CI failing if authentication is not included in the e2e tests.

@edlerd I'm going to need some assistance in setting up some additional environment secrets for GA i.e. `OIDC_ISSUER`, `OIDC_CLIENT_ID`, `OIDC_AUDIENCE`

2024-07-05 09:32 UTC, mas-who commented
@markylaing #35 is now merged and I have dropped the commits in this PR and rebased.

2024-07-08 08:37 UTC, markylaing submitted a review, later dismissed
I think we can move forward with this for now.

I'm not a fan of the additional endpoint for the OIDC callback (nor adding the cookies to the request body), but as this is circumventing a limitation of microcluster it'll have to do for now. There may be a better way this more generally (see https://github.com/canonical/lxd/issues/13644#issuecomment-2213288260).

When we have a solution to https://github.com/canonical/lxd/issues/13644 we will also move the `oidc` package into `lxd/shared` and make it more of a library. At that point we'll need to revisit this and make changes.

2024-07-08 08:37 UTC, markylaing commented on internal/oidc/oidc.go
> +				IdentityType: api.IdentityTypeOIDCClient,
Did we say we'd remove `IdentityType` for now since only OIDC authentication is possible?

2024-07-08 08:37 UTC, markylaing commented on internal/oidc/oidc.go
> +func (o *Verifier) WriteTokenToCookies(w http.ResponseWriter, idToken string, refreshToken string) error {
Does this need to be exported now that the auth context is no longer used?

2024-07-08 08:37 UTC, markylaing commented on internal/oidc/oidc.go
> +	w.Header().Set("X-LXD-OIDC-audience", o.audience)
These are not needed without the CLI. (If you do need OIDC for a CLI at some point, we'll also need to change the headers from `X-LXD-OIDC-*` to something like `X-LXD-site-manager-OIDC-*`).

2024-07-08 08:37 UTC, markylaing commented on internal/oidc/oidc.go
> +func (o *Verifier) authenticateAccessToken(ctx context.Context, accessToken string) (*AuthenticationResult, error) {
Also not needed without the CLI. Although you might need this later. At that point we can revisit making these functions available via the LXD shared package.

2024-07-08 08:37 UTC, markylaing commented on internal/state/state.go
> +	MicroCluster *microcluster.MicroCluster
This seems very circular. It's not a blocker, but could you create an issue in microcluster to address this please?

The microcluster state should contain everything you need in a handler. IIRC this gives you access to a method that can make requests to a single member without making a client for all members in the cluster? If so, I think this should be defined on state.

2024-07-08 10:11 UTC, mas-who commented on internal/oidc/oidc.go
> +				IdentityType: api.IdentityTypeOIDCClient,
Aaah yes, thanks will remove.

2024-07-08 10:27 UTC, mas-who commented on internal/oidc/oidc.go
> +func (o *Verifier) WriteTokenToCookies(w http.ResponseWriter, idToken string, refreshToken string) error {
We need `WriteTokenToCookies` for handling the tokens returned in the response of a forwarded idp callback request. This is due to the microcluster restriction that we do not receive the full response object from a client query function, this means I can't extract the session cookies from the response headers and forward them to the browser. Instead, I have to return the oidc tokens, generate the cookies and write them to the response for the browser.

2024-07-08 10:27 UTC, mas-who commented on internal/oidc/oidc.go
> +	w.Header().Set("X-LXD-OIDC-audience", o.audience)
I will remove everything from the oidc package that's not needed in site manager for now :+1:

2024-07-08 10:31 UTC, mas-who commented on internal/oidc/oidc.go
> +func (o *Verifier) authenticateAccessToken(ctx context.Context, accessToken string) (*AuthenticationResult, error) {
removing this method as well as usage :+1:

2024-07-08 10:42 UTC, mas-who commented on internal/state/state.go
> +	MicroCluster *microcluster.MicroCluster
Yes agreed, I will open an issue for this.

FYI, there is another way to forward a request to another cluster member in microcluster. For a `rest.EndpointAction`, we can use the `ProxyTarget` flag to forward a request to a member. However, this requires the `target` query param to be set in the idp callback url, which I think isn't appropriate for the oidc flow.

2024-07-08 12:41 UTC, mas-who commented on internal/state/state.go
> +	MicroCluster *microcluster.MicroCluster
created an [issue](https://github.com/canonical/microcluster/issues/171) in microcluster for this.

2024-07-08 12:45 UTC, mas-who commented
> I think we can move forward with this for now.
> 
> I'm not a fan of the additional endpoint for the OIDC callback (nor adding the cookies to the request body), but as this is circumventing a limitation of microcluster it'll have to do for now. There may be a better way this more generally (see [canonical/lxd#13644 (comment)](https://github.com/canonical/lxd/issues/13644#issuecomment-2213288260)).
> 
> When we have a solution to [canonical/lxd#13644](https://github.com/canonical/lxd/issues/13644) we will also move the `oidc` package into `lxd/shared` and make it more of a library. At that point we'll need to revisit this and make changes.

@markylaing I've created the following issues to keep track of the above:
#39 - Improve approach to handling oidc login flow across multiple cluster members
#40 - use LXD shared oidc library when ready
#41 - remove `POST /oidc/callback endpoint` (created upstream microcluster [issue](https://github.com/canonical/microcluster/issues/170))

2024-07-08 12:50 UTC, markylaing commented
> > I think we can move forward with this for now.
> > I'm not a fan of the additional endpoint for the OIDC callback (nor adding the cookies to the request body), but as this is circumventing a limitation of microcluster it'll have to do for now. There may be a better way this more generally (see [canonical/lxd#13644 (comment)](https://github.com/canonical/lxd/issues/13644#issuecomment-2213288260)).
> > When we have a solution to [canonical/lxd#13644](https://github.com/canonical/lxd/issues/13644) we will also move the `oidc` package into `lxd/shared` and make it more of a library. At that point we'll need to revisit this and make changes.
> 
> @markylaing I've created the following issues to keep track of the above: #39 - Improve approach to handling oidc login flow across multiple cluster members #40 - use LXD shared oidc library when ready #41 - remove `POST /oidc/callback endpoint` (created upstream microcluster [issue](https://github.com/canonical/microcluster/issues/170))

Cool. I've also created an issue to define the handler types in microcluster so that you don't need to do that here.

2024-07-16 07:41 UTC, edlerd requested changes
Best to factor out the forwarding logic to keep this one concise.

2024-07-16 07:41 UTC, edlerd commented on .github/workflows/pr.yaml
> +
```suggestion
```
This shouldn't be part of this PR.

2024-07-16 07:41 UTC, edlerd commented on entrypoint
> +tail -f /dev/null
```suggestion
tail -f /dev/null

```

2024-07-16 07:41 UTC, edlerd commented on internal/api/auth.go
> +				MemberAddress: innerState.Address().URL.String(),
This will make the internal address publicly visible. I am not sure if this is a good idea. Can we make the whole forwarding of requests a separate PR to have only the login in here?

2024-07-16 07:41 UTC, edlerd commented on ui/src/App.tsx
> +
The loading experience of the login page is blinking in and out the navigation for some time. Can we hide the navigation until the auth is loaded to avoid this flickering? Or always display the navigation, also logged out.

2024-07-16 07:41 UTC, edlerd commented on ui/src/context/auth.tsx
> +};
This should be better abstracted and decoupled.

We should not expose `setIsAuthenticated` outside this hook. Figure the isAuthenticated state inside this hook with a local query. Invalidate the cache for that query on logout to trigger a refresh, but do not directly couple it to this hook.

2024-07-16 07:41 UTC, edlerd commented on internal/oidc/oidc.go
> +	identityCache       *identity.Cache
```suggestion
```
Seems to be unused?

2024-07-16 07:41 UTC, edlerd commented on internal/oidc/oidc.go
> +	accessTokenVerifier *op.AccessTokenVerifier
```suggestion
```
Unused?

2024-07-16 07:41 UTC, edlerd commented on internal/oidc/oidc.go
> +	ID            string
```suggestion
```
unused?

2024-07-16 07:41 UTC, edlerd commented on internal/oidc/oidc.go
> +	return result, resp, err
If we reach this, we will return an empty result and response. I think we should throw an error here instead.

2024-07-16 07:41 UTC, edlerd commented on internal/oidc/oidc.go
> +			http.Redirect(w, r, "/ui", http.StatusMovedPermanently)
It would be nice if the ui sets a `next` param on starting the flow. We should store it in the state token and unpack it here to forward to the next url. That way in case a user accesses an internal url, they will land on that url after login.

2024-07-16 07:41 UTC, edlerd commented on internal/oidc/oidc.go
> +	} else if sessionIDCookie == nil {
```suggestion
	}
	if sessionIDCookie == nil {
```

2024-07-16 09:39 UTC, mas-who commented on ui/src/App.tsx
> +
quick fix is to set `const isAuthError = isLoading || error?.message === "not authorized";`. In general I think the auth logic in the UI will need some refactoring once we have the `/1.0` endpoint.

2024-07-16 11:41 UTC, mas-who commented on ui/src/context/auth.tsx
> +};
Thanks I've moved the query from `App.tsx` to `auth.tsx` and also added a `FIXME` comment to say the query should reach out to `/1.0` once the endpoint is ready. I've also moved the `logout` helper from lxd-ui. We don't need to do a query invalidation since we are setting `window.location.href` when logging out which triggers a page reload.

2024-07-16 11:45 UTC, mas-who commented on internal/oidc/oidc.go
> +	identityCache       *identity.Cache
I kept it previously because the `identityCache` will be needed if we perform access token verification which is used for device grant flow in lxd. I think it's easy enough to add it back later if we need it, so removing this now.

2024-07-16 11:45 UTC, mas-who commented on internal/oidc/oidc.go
> +	accessTokenVerifier *op.AccessTokenVerifier
related to the earlier comment about dependency for device grant flow. Will remove for now as it's not needed.

2024-07-16 11:56 UTC, mas-who commented on internal/oidc/oidc.go
> +	ID            string
The `StateToken` gets base64 encoded and will be passed to the idp as the `state` query param in the callback url. The idea here is that the id field in the token would uniquely identify the current login flow otherwise multiple users triggering the login flow would have the exact same `state`. The query param is used by zitadel internally to verify the login session.

That being said, since we are going to strip out the logic for forwarding idp callback request. `StateToken` will no longer be relevant in the context of this PR. So going to resolve this convo for now.

2024-07-16 12:00 UTC, mas-who commented on internal/oidc/oidc.go
> +	return result, resp, err
sorry I'm not sure if I follow, if we reach this point we would have valid result and response. Although we should return `nil` for error.

2024-07-16 12:03 UTC, mas-who commented on internal/api/auth.go
> +				MemberAddress: innerState.Address().URL.String(),
as discussed, will strip out the logic for forwarding request into a separate PR for future reference.

2024-07-16 12:03 UTC, edlerd commented on internal/oidc/oidc.go
> +	return result, resp, err
I was thinking we can reach here in case id-token and refresh-token are both empty.

2024-07-16 12:11 UTC, mas-who commented on internal/oidc/oidc.go
> +	return result, resp, err
aah I see, this is taken care of in `authenticateIDToken` since if both tokens are empty, then it would result in a token refresh error.

2024-07-16 12:13 UTC, mas-who commented on internal/oidc/oidc.go
> +			http.Redirect(w, r, "/ui", http.StatusMovedPermanently)
Yeah sounds good. Will implement this logic once I have moved out the forwarding request logic shortly.

2024-07-16 14:31 UTC, mas-who commented on internal/oidc/oidc.go
> +			http.Redirect(w, r, "/ui", http.StatusMovedPermanently)
@edlerd implemented this. It would be easy to check the changes in the last commit.

2024-07-16 14:38 UTC, edlerd commented on internal/oidc/oidc.go
> +	return result, resp, err
Problem is we won't enter that branch as it is guarded by `if idToken != "" || refreshToken != "" {`

2024-07-16 14:57 UTC, edlerd commented on internal/oidc/oidc.go
> +	return result, resp, err
Discussed in person, there is a check upstream in `!s.OIDCVerifier.IsRequest(r)` guarding from this case.

2024-07-16 15:47 UTC, edlerd requested changes

2024-07-16 15:47 UTC, edlerd commented on ui/src/context/auth.tsx
> +        isAuthenticated: !isAuthError,
```suggestion
  const isAuthenticated = !isLoading && error?.message === "not authorized";

  return (
    <AuthContext.Provider
      value={{
        isAuthenticated,
```
Seems easier to reason about?

2024-07-16 15:57 UTC, edlerd approved these changes
LGTM :)

2024-07-16 16:02 UTC, edlerd requested changes

2024-07-16 16:02 UTC, edlerd commented on ui/src/context/auth.tsx
> +  const isAuthenticated = !isLoading && error?.message === "not authorized";
```suggestion
  const isAuthenticated = !isLoading && error?.message !== "not authorized";
```

2024-07-17 08:07 UTC, edlerd approved these changes
Good work, thanks for adding login :)

2024-07-17 08:43 UTC, merged