Setup management listener using `extensionServers` [WD-11937]
canonical/microcloud-cluster-manager pull request #15
Opened 2024-06-07 16:22 UTC by mas-who

## Done
 - removed the old way of registering endpoints using `extendedEnpoints`
 - added `server.go` which has `Servers` slice. The network listeners are defined in this slice.
 - added all existing endpoints to the site management listener which will be grouped with the core listener
 - server static assets for the frontend via `/ui` instead of `/1.0/ui`
 
## Note
 - Originally enabled by this [PR](https://github.com/canonical/microcluster/pull/130).
 - This PR is dependent on the upstream microcluster [PR](https://github.com/canonical/microcluster/pull/142) getting merged.
 - relating to this [issue](https://github.com/canonical/microcluster/issues/139), it seems like currently there is no way to pass the server structs to microcluster during cluster initialisation. This is not a problem for the site management listener since its endpoints resides with the core listener. However, the status listener will need to have its address passed during initialisation.

2024-06-14 13:15 UTC, mas-who commented on go.mod
> +replace github.com/canonical/microcluster => ../microcluster
We can use this to test microcluster dependency locally. This will be removed after upstream PR gets merged.

2024-06-14 14:43 UTC, edlerd commented on internal/api/server.go
> +					uiImgCmd,
I think we should add a handler for the `/` route, to redirect to `/ui` from the go side. We do have it in the App.tsx for the dotrun/ dev server side. But in production we'd need it as well.

2024-06-14 14:58 UTC, mas-who commented on internal/api/server.go
> +					uiImgCmd,
That makes sense, although currently it's not possible to do that with microcluster because there is a handler for `/` that's registered before the user defined endpoints. See [here](https://github.com/canonical/microcluster/blob/c2ff70b3b3e39b601727ebda4a4a43c9c0f0de57/internal/daemon/daemon.go#L321).

I see lxd has a pretty reasonable [approach](https://github.com/canonical/lxd/blob/45f8fa530224da96acd25ac5e450f8d851be2022/lxd/api.go#L166) for the redirect, I'm gonna see if I can get that into the upstream PR.

Edit: might be tricky to add it to microcluster exactly how lxd does it because we can't assume in microcluster that there will be a `/ui` path.

2024-06-14 15:30 UTC, mas-who commented on internal/api/server.go
> +					uiImgCmd,
So I got a [workaround](https://github.com/canonical/microcluster/pull/142/commits/817979f5a17227cdbed5a40dc19885cd8eeb0aef) in the same upstream PR. Idea is just to change the ordering of route definition. If a handler for `/` is defined in a downstream app, then that handler will be used over the one defined in microcluster.

2024-06-20 08:04 UTC, edlerd requested changes

2024-06-20 08:04 UTC, edlerd commented on Makefile
> +	rm -rf internal/api/static &>/dev/null
I think this is still needed, otherwise we might leave orphaned files in there from previous runs.

2024-06-20 08:04 UTC, edlerd commented on internal/api/server.go
> +	{
Should we assign this struct to a variable named `SiteManagementListener` and use it here in favour of the comment? I think that might enhance structure and readability.

2024-06-20 08:04 UTC, edlerd commented on internal/api/types/server.go
> +	CoreEndpointPrefix types.EndpointPrefix = "1.0"
Maybe better `ApiVersionPrefix`?

2024-06-20 08:04 UTC, edlerd commented on internal/api/types/server.go
> +	PublicEndpointPrefix types.EndpointPrefix = ""
This is not really public, is it? Maybe better `NoPrefix` or `RootPrefix`?

2024-06-20 08:04 UTC, edlerd commented on ui/vite.config.ts
> -    },
Why remove this? I think this is still needed.

2024-06-20 08:12 UTC, mas-who commented on Makefile
> +	rm -rf internal/api/static &>/dev/null
The intention here is to cleanup the static directory so it's a clean copy from `/ui/static` to `/internal/api/static` every time?

2024-06-20 08:47 UTC, edlerd commented on Makefile
> +	rm -rf internal/api/static &>/dev/null
Sorry, I was confused and thought you removed this line, but actually are adding it.

2024-06-20 09:37 UTC, mas-who commented on internal/api/server.go
> +	{
good idea! :)

2024-06-20 09:38 UTC, mas-who commented on internal/api/types/server.go
> +	PublicEndpointPrefix types.EndpointPrefix = ""
Agreed, currently it's all public endpoints e.g. /ui, /oidc etc. But I think this is not guaranteed. Let's use `NoPrefix` since it's explicit

2024-06-20 09:59 UTC, mas-who commented on ui/vite.config.ts
> -    },
It was causing proxy errors in the dotrun log output. The fix is actually to change the `target`, I've made the update

2024-06-20 10:24 UTC, edlerd approved these changes
Code and QA LGTM

2024-06-20 10:29 UTC, merged