[WD-12166] feat: Added Login/Logout button (ui) for LXD-SM.
canonical/microcloud-cluster-manager pull request #20
Opened 2024-06-19 17:01 UTC by Kxiru

Tasks:
* Added a route to the Login Page
* Added a Login page using LoginPageLayout
* Added a Login button to the login page and a logout button to the SiteList page.

Login Page
![image](https://github.com/canonical/lxd-site-manager/assets/58699506/cc23f203-07cf-40bc-9723-83ec2a7d7c27)

Logout Button
![image](https://github.com/canonical/lxd-site-manager/assets/58699506/f59dcc6b-501e-498b-bbf2-b7e4c6da8e66)

2024-06-19 19:18 UTC, edlerd requested changes

2024-06-19 19:18 UTC, edlerd commented on ui/src/App.tsx
> +        <Route path="/ui/login" element={<Login />} />
```suggestion
        <Route path="/ui" element={<Login />} />
```
I think this should be the default route, the one below can be /ui/sites

2024-06-19 19:18 UTC, edlerd commented on ui/src/pages/Login.tsx
> +        <Link to={"/1.0/oidc/login"}>Login (OIDC)</Link>
There shouldn't be a link inside a button, you can set the href param on the button instead. The caption should be "Login", no need to point out we are using oidc to the user.

2024-06-19 19:18 UTC, edlerd commented on ui/src/pages/Login.tsx
> +    <LoginPageLayout title="Login">
```suggestion
    <LoginPageLayout title="Login to LXD site manager">
```
Maybe better?

2024-06-19 19:18 UTC, edlerd commented on ui/src/pages/sites/SiteList.tsx
> +        <Link to={"/1.0/oidc/logout"}>Login (OIDC)</Link>
```suggestion
        <Link to="/1.0/oidc/logout">Logout</Link>
```

2024-06-20 07:50 UTC, mas-who commented on ui/src/pages/Login.tsx
> +        <Link to={"/1.0/oidc/login"}>Login (OIDC)</Link>
Please also change the link url to `/oidc/login` instead, we planning on getting rid of the `/1.0` prefix for login endpoints

2024-06-20 07:50 UTC, mas-who commented on ui/src/pages/sites/SiteList.tsx
> +        <Link to={"/1.0/oidc/logout"}>Login (OIDC)</Link>
```suggestion
        <Link to={"/oidc/logout"}>Login (OIDC)</Link>
```

2024-06-20 10:20 UTC, edlerd requested changes
Code and QA LGTM, can you ensure the commit message is reflecting the changes?

For the future, you don't need to use the project name in the branch name, as the branches are namespaced per project.

2024-06-20 10:21 UTC, edlerd commented
You can use `git commit --amend -a -S -s` to change the commit message.

2024-06-20 11:04 UTC, edlerd approved these changes
All good now, thanks for adding it and providing feedback to improve the setup / readme when starting.

Just one issue with the failing e2e test, I think we need to update the test with the new home page title.

2024-06-20 11:09 UTC, Kxiru commented
> All good now, thanks for adding it and providing feedback to improve the setup / readme when starting.
> 
> Just one issue with the failing e2e test, I think we need to update the test with the new home page title.

All fixed!

2024-06-20 11:29 UTC, Kxiru commented
Although I believe the Chromium e2e test is failing incorrectly. As the information is it pulling is outdated. The title of the Login.tsx page has definitely been changed, and it is aligned with the correct navigation url.

2024-06-20 11:50 UTC, edlerd commented
> Although I believe the Chromium e2e test is failing incorrectly. As the information is it pulling is outdated. The title of the Login.tsx page has definitely been changed, and it is aligned with the correct navigation url.

This is probably a timing issue. Because the login page is changing the title after the initial loading. You could also change the test to rely on the /ui/sites page to have the previous title. After all that is the site list spec test.

2024-06-21 09:34 UTC, Kxiru commented
@edlerd After the alterations we made yesterday, the tests are still failing. How would you like me to approach this?

2024-06-21 11:29 UTC, edlerd commented
> @edlerd After the alterations we made yesterday, the tests are still failing. How would you like me to approach this?

I think we are missing the latest changes from the main branch and that's why the request to /ui/sites is 404. Can you rebase on main and force-push the update? That should fix it.

2024-06-21 14:39 UTC, Kxiru commented
I have already rebased and forced pushed here :(. Which changes are missing?

2024-06-22 08:26 UTC, edlerd commented
> I have already rebased and forced pushed here :(. Which changes are missing?

You are right indeed. I think this is because /ui/sites is a new path that needs to be registered in go explicitly. @mas-who can we make it like in LXD where all paths under /ui/* serve the html/js frontend files? If not, can you help to register the new path in go?

2024-06-22 10:34 UTC, mas-who commented
> > I have already rebased and forced pushed here :(. Which changes are missing?
> 
> You are right indeed. I think this is because /ui/sites is a new path that needs to be registered in go explicitly. @mas-who can we make it like in LXD where all paths under /ui/* serve the html/js frontend files? If not, can you help to register the new path in go?

I've created a PR #22 to resolve the issue here. Left some comments on that PR for context and I think there is still a bit of work to be done to streamline how the ui should be served.

2024-06-24 09:09 UTC, Kxiru commented
@edlerd , @mas-who , thanks for making the fixing PR! What does this mean for this PR though? :)

2024-06-24 09:11 UTC, mas-who commented
> @edlerd , @mas-who , thanks for making the fixing PR! What does this mean for this PR though? :)

The other PR will need to be merged first, then the failing CI here should pass since I've tested the changes with your PR.

2024-06-24 09:36 UTC, Kxiru commented
> > @edlerd , @mas-who , thanks for making the fixing PR! What does this mean for this PR though? :)
> 
> The other PR will need to be merged first, then the failing CI here should pass since I've tested the changes with your PR.

As vigilant as ever. Thanks a bunch!

2024-06-24 12:30 UTC, mas-who commented
@Kxiru the #22 just got merged. Can you rebase the changes and push again

2024-06-24 13:02 UTC, merged