add DELETE endpoint for `/sites/:name` [WD-11657]
canonical/microcloud-cluster-manager pull request #25
Opened 2024-06-26 16:41 UTC by mas-who

## Done
 - Added a DELETE endpoint for `1.0/sites/:name`
 - Added some buttons in the UI for testing the delete endpoint

## Context
 - With #24 merged, this has become quite easy since we have already implemented the db methods.

2024-06-26 16:52 UTC, mas-who commented
As a side note, I checked the delete on cascade on `site_details` and `site_member_statuses`, works nicely.

2024-06-26 18:54 UTC, edlerd requested changes
Shall we keep this as draft until the oidc PR is merged and include the permission checks here directly?

2024-06-26 18:54 UTC, edlerd commented on ui/src/pages/sites/SiteList.tsx
> +  };
This should be in a dedicated DeleteSiteButton component together with the button rendering. We should rely on cache invalidation instead of hooking into refetch to reduce coupling and to keep the delete function reusable.

2024-06-27 09:24 UTC, mas-who commented
> Shall we keep this as draft until the oidc PR is merged and include the permission checks here directly?

Yeah sure, we can hold off on this PR until the authentication PR is merged.

2024-06-28 12:05 UTC, mas-who commented on ui/src/pages/sites/SiteList.tsx
> +  };
Made the suggested change :slightly_smiling_face:

2024-06-28 12:06 UTC, mas-who commented
@edlerd as discussed yesterday, I think we can merge this one if it's ready. I will apply the access handler on the oidc PR to this endpoint

2024-06-28 13:04 UTC, edlerd approved these changes
LGTM :+1:

2024-06-28 13:07 UTC, merged