feat: LXD-SM setup application layout for the UI [WD-12637]
canonical/microcloud-cluster-manager pull request #28
Opened 2024-07-01 12:03 UTC by Kxiru

- Added Navigation.tsx in it's own Components folder, as well as Logo and NavLink.
- Implemented the ApplicationLayout structure from react-components.
- Added a BaseLayout component as in LXD-UI.

![image](https://github.com/canonical/lxd-site-manager/assets/58699506/5c5a0eb4-96bc-4c18-8608-309f2f9b2667)

2024-07-01 17:15 UTC, edlerd reviewed
As discussed, let's add the navigation in this PR as well.

2024-07-01 20:01 UTC, mas-who commented on ui/src/Components/Navigation.tsx
> +import { FC } from "react";
can we have the `Components` folder not capitalised?

2024-07-01 20:12 UTC, mas-who commented on ui/src/Root.tsx
> +      <div id="l-application" className="l-application" role="presentation">
@edlerd @Kxiru , I think since we are adding the application layout, we should probably also create a layout component similar to the `BaseLayout` component in lxd-ui? Maybe we should use composite components pattern to avoid passing down too many props

2024-07-03 17:17 UTC, mas-who requested changes
Providing some feedback so far, I haven't completely reviewed everything yet. Will continue tomorrow.

![Screenshot from 2024-07-03 19-16-49](https://github.com/canonical/lxd-site-manager/assets/151511568/24777a24-888c-4807-9fb0-00fc2e1ae00b)

2024-07-03 17:17 UTC, mas-who commented on ui/package.json
> +    "@use-it/event-listener": "^0.1.7",
please remove `^`

2024-07-03 17:17 UTC, mas-who commented on ui/src/Root.tsx
> +        <AppStatus />
we can leave out `AppStatus` for now I rate. AFAIK we don't have a status bar in the design yet correct?

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/BaseLayout.tsx
> +    <main className={classnames("l-main", mainClassName)}>
`AppMain` already has the `l-main` class, so you can remove this `main` element. You can also just pass `mainClassName` to `AppMain`. See [AppMain](https://github.com/canonical/react-components/blob/main/src/components/ApplicationLayout/AppMain/AppMain.tsx) in react-components. It has `classnames` implemented so your custom classes will be appended to `l-main`.

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/BaseLayout.tsx
> +        <Panel>
The `Panel` component already has the div with `p-panel__header`, `p-panel__title`, `p-panel__controls` and `p-panel__content` classes. You should use the relevant props on the `Panel` component to modify relevant aspects of the panel section. see [docs](https://canonical.github.io/react-components/?path=/docs/components-panel--docs)

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Logo.tsx
> +// import { useProject } from "context/project";
remove comments through out please

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Logo.tsx
> +  const getLogoLink = () => {
we can remove this function for now

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/NavLink.tsx
> +  // ignore last char to consider /instances and /instance as active
these comments are specific to lxd-ui. The logic is still relevant though. I suggest we change to to something a bit more generic like "ignore last char to consider plural form of url paths".

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/NavLink.tsx
> +  // this caters for more custom url matches for link to be active e.g. /identities & /identity/oidc etc
same thing here, maybe just remove the example part of the comment

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +  // const { isAuthenticated } = useAuth();
remove

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +          controls={
`controls` is already a child of `p-panel__header`. So this is incorrect. You should use `controls`, `logo` and `toggle` props from the `Panel` component to replicate this section (relative to lxd-ui). See the [Panel](https://github.com/canonical/react-components/blob/main/src/components/Panel/Panel.tsx) component.

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +        ></Panel>
If there is no child, prefer self-closing tags e.g. `<Panel />` instead of `<Panel></Panel>`

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +        className={classnames("l-navigation", {
no need to have `l-navigation` here, it's already in `AppNavigation`

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +          "is-scroll": scroll,
we don't need `is-scroll` in site manager yet. We can remove this for now. Please remove the relevant state, effects and sass styles as well.

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +        <SideNavigation>
Why are we using `SideNavigation` here. To replicate lxd-ui, `AppNavigation` already has the `l-navigation__drawer` class inside the component

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +          <div className="p-panel is-dark">
We should use the `Panel` component here.

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +                      <SideNavigationItem href={`/ui/sites`}>
same comment as above, why are we using `SideNavigationItem` here?

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +                <ul className="p-side-navigation__list sidenav-top-ul">
@edlerd are we going to have the same navigation structure as lxd-ui? i.e. bottom half of the nav has fixed height and sticks to the bottom of the viewport. If so, we should probably bring in the vertical adjustment logic now.

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +                          onClick={() => {
let's put this callback into a `handleLogin` function

2024-07-03 17:17 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +                        onClick={() => {
let's put this callback into a `handleLogout` function. Move logic from `logoutFunc` into `handleLogout`

2024-07-03 17:38 UTC, Kxiru commented on ui/src/Root.tsx
> +        <AppStatus />
Not yet, I suppose. Done!

2024-07-03 17:41 UTC, Kxiru commented on ui/src/components/BaseLayout.tsx
> +    <main className={classnames("l-main", mainClassName)}>
I believe I forgot to take out the main element. Thanks for spotting this!

2024-07-03 17:45 UTC, Kxiru commented on ui/package.json
> +    "@use-it/event-listener": "^0.1.7",
We need this for context/Menucollapsed.tsx. Unless you have a workaround?

2024-07-03 17:55 UTC, mas-who commented on ui/package.json
> +    "@use-it/event-listener": "^0.1.7",
I meant remove the `^` symbol to keep version fixed

2024-07-04 08:36 UTC, mas-who reviewed
some more comments for code changes.

2024-07-04 08:36 UTC, mas-who commented on ui/src/context/menuCollapsed.tsx
> +import { useState } from "react";
I think this file can be simplified for now. For `collapseOnMediumScreen`, you can remove the if statement that's checking the event detail since it's related to `spice` in lxd-ui and `sfp-toggle` event which currently we don't have in site manager. You can also remove all logic related to search filter here. We should start off with the minimal amount of logic necessary when copying over existing code, so we don't add complexity to this project if not needed.

2024-07-04 08:36 UTC, mas-who commented on ui/src/pages/Login.tsx
> +      <Link href="/ui/sites" className="p-button">
why is this changed? We need to have the `/oidc/login` path so that a request will be sent to the backend.

2024-07-04 08:36 UTC, mas-who commented on ui/src/pages/sites/SiteList.tsx
> +      <div>
we should apply the [vanilla grid layout](https://vanillaframework.io/docs/patterns/grid) here. The equivalent components in react-components are [Row](https://github.com/canonical/react-components/tree/main/src/components/Row) and [Col](https://github.com/canonical/react-components/tree/main/src/components/Col). The grid pattern in vanilla aligns elements within a 12 column grid, which is used for all canonical apps/websites, so it's a good opportunity to familiarise yourself with it.

2024-07-04 08:36 UTC, mas-who commented on ui/src/pages/sites/SiteList.tsx
> +        <Link href="/oidc/logout" className="p-button">
we can remove this logout button here.

2024-07-04 08:36 UTC, mas-who commented on ui/src/sass/_pattern_icon.scss
> +@mixin lxdui-icon-sidebar-collapse() {
we should replace `lxdui` in these mixin names. perhaps something like `sidebar-collapse-icon` and `custom-p-icon`. Prefer having more generic naming here instead of adding a prefix of `lxdsm` or something alike since we might change `site manager` to `cluster manager` later, so let's try avoid having to come back for updates where possible.

2024-07-04 08:36 UTC, mas-who commented on ui/src/sass/styles.scss
> +@include lxdui-p-icon;
change mixin name

2024-07-04 08:36 UTC, mas-who commented on ui/src/sass/_pattern_navigation.scss
> +  .l-navigation__drawer {
this class isn't used anywhere, but we probably should remove it since it was definitely needed in lxd-ui. This is probably related to my previous comment about using the `SideNavigation` component from react-components. Would you please investigate.

2024-07-04 08:36 UTC, mas-who commented on ui/src/sass/_pattern_navigation.scss
> +.accordion-nav-menu {
this class is not used, please remove, if we need it later we can copy it over from lxd-ui

2024-07-04 08:36 UTC, mas-who commented on ui/src/sass/_pattern_navigation.scss
> +.accordion-nav-secondary {
we can remove this

2024-07-04 08:38 UTC, Kxiru commented on ui/src/components/Navigation.tsx
> +          controls={
Thank you for the link, however I still do not understand what toggle is supposed to be.  By name it is implied to be a function but by the link you sent me, it is implied to be a component. However if the Button component is passed through to toggle instead, then there are no longer any controls. Please could you clarify what you mean, here?
![image](https://github.com/canonical/lxd-site-manager/assets/58699506/9c5cce60-e147-4db9-aadc-63c65b626b57)

2024-07-04 08:39 UTC, mas-who commented
Currently the `hr` element sit right below the top half of the navigation.
![Screenshot from 2024-07-04 10-36-37](https://github.com/canonical/lxd-site-manager/assets/151511568/b6c22555-3f8e-43b8-9ae6-7d12cab54e5b)

I think it should sit above the bottom half of the navigation similar to lxd-ui, no?
![Screenshot from 2024-07-04 10-37-55](https://github.com/canonical/lxd-site-manager/assets/151511568/865583cb-6451-4073-ba0d-d313ebbca3e2)

2024-07-04 09:11 UTC, Kxiru commented on ui/src/components/Navigation.tsx
> +          <div className="p-panel is-dark">
The transfer was well and good until Toggle got in the way again. This is all that can be passed through to it (see screenshot), I can't find much documentation on it, and when used as such the toggle does not appear in LXDSM. I am open to further investigation.
![image](https://github.com/canonical/lxd-site-manager/assets/58699506/f67f4484-3f46-48dc-8fe2-535772c1a9a4)

2024-07-04 09:26 UTC, Kxiru commented on ui/src/pages/sites/SiteList.tsx
> +      <div>
Sorry, I don't understand, you would like me to implement a grid layout in Base Layout? Could you please provide an example of this?

2024-07-04 09:28 UTC, Kxiru commented on ui/src/sass/_pattern_navigation.scss
> +  .l-navigation__drawer {
I believe we are good to remove this.

2024-07-04 09:56 UTC, edlerd commented on ui/src/components/Navigation.tsx
> +                <ul className="p-side-navigation__list sidenav-top-ul">
That is not decided yet, I'd keep the nav simple for now.

2024-07-04 11:24 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +          controls={
Yeah this looks good now. I think since you are using `controls` it is fine. `toggle` would be a replacement for your current implementation which I don't think is necessary.

2024-07-04 11:32 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +          <div className="p-panel is-dark">
can't find the original code so it's a bit confusing to review now since the context is lost, but I think your current implementation using `controls` is fine. Related to a previous comment, I think `toggle` is just a convenient way to add a toggle button for the panel, you can achieve the same using the `controls` prop.

2024-07-04 11:34 UTC, mas-who commented on ui/src/pages/sites/SiteList.tsx
> +      <div>
see [ClusterList.tsx](https://github.com/canonical/lxd-ui/blob/main/src/pages/cluster/ClusterList.tsx) from lxd-ui. The `Row` component wraps around children components to establish the 12 column grid. You can achieve variations of the grid pattern using combination of the `Row` and `Col` components which relates to the `row` and `col` classes in vanilla.

2024-07-04 13:56 UTC, Kxiru commented on ui/src/pages/sites/SiteList.tsx
> +      <div>
Implemented. Looking much better!

2024-07-04 20:42 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +          logo={<Logo />}
missing a prop here, `stickyHeader` on `Panel` should be set

2024-07-04 20:49 UTC, mas-who reviewed
almost there, few minor comments :slightly_smiling_face:

2024-07-04 20:49 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +          {" "}
this empty space shouldn't be here right?

2024-07-04 20:49 UTC, mas-who commented on ui/src/components/Navigation.tsx
> +                  <NavLink
each `NavLink` should be inside an `li`

2024-07-04 20:49 UTC, mas-who commented on ui/src/pages/sites/SiteList.tsx
> +        <div>
this `div` won't be needed since `Row` is a div already

2024-07-04 20:59 UTC, mas-who commented
great work @Kxiru it's looking like a proper app now :smile: 

one query from me. I think the app title next to the logo is way too close to the edge of the navigation and it looks cramped. Not sure how we deal with this though since there isn't enough space. @piperdeck any ideas?

![Screenshot from 2024-07-04 22-55-43](https://github.com/canonical/lxd-site-manager/assets/151511568/da13b489-bd99-4bae-8bb5-ee4251f32da8)

2024-07-05 10:19 UTC, mas-who commented on ui/src/sass/styles.scss
> +@import "settings";
final comment here. Can you add the below style to this file? This will remove the max-width constraint allowing the `row` grid to not have margin for large screen sizes. This should align the header and body of the page nicely.

```
.l-main .row {
  max-width: none;
}
```

2024-07-05 10:23 UTC, Kxiru commented on ui/src/sass/styles.scss
> +@import "settings";
All done! If that's all, then I'm just awaiting an approval now :)

2024-07-05 10:24 UTC, mas-who approved these changes

2024-07-05 10:25 UTC, mas-who commented
LGTM :+1: Thanks for this!

2024-07-05 10:27 UTC, merged