add POST `/1.0/external-site-tokens` endpoint [WD-12698]
canonical/microcloud-cluster-manager pull request #29
Opened 2024-07-01 19:58 UTC by mas-who

## Done

- [x] setup `POST /1.0/external-site-join-token` 
- [x] setup utility function to calculate site manager addresses
- [x] setup `GET /1.0/external-site-join-token` 
- [x] setup `DELETE /1.0/external-site-join-token/:site_name`  

## Note
 - I have included a commit here that introduced experimental hooks on cluster bootsrap and member join. This is for testing the site manager address generation logic. I will drop the commit once the PR is approved.
 - The manager address logic will likely fail before we get the ability to provide network listener with custom addresses.

2024-07-03 06:45 UTC, edlerd requested changes

2024-07-03 06:45 UTC, edlerd commented on internal/api/tokens.go
> +	if payload.Expiry != (time.Time{}) && payload.Expiry.Before(time.Now()) {
Expiry should also be set, it is not allowed to be empty.

2024-07-03 06:45 UTC, edlerd commented on internal/api/tokens.go
> +	// TODO: these addresses should be calculated based on configs, extract to util function
We have defined a 3 way options:
1. config key if it is present with the array of members, unsorted just as is.
3. the external ip on the members table, this should be sorted so db-leader is in 1st place.
4. the default address on the members table, this should be sorted so db-leader is in 1st place.

We should check from 1 and fall back successively until we reach 3. This should be in a util function as the comment suggests.

2024-07-03 06:45 UTC, edlerd commented on internal/api/types/tokens.go
> +type ExternalSiteTokenBody struct {
How do we share this and other structs with LXD source that is receiving and unpacking them?

2024-07-03 07:41 UTC, mas-who commented on internal/api/tokens.go
> +	if payload.Expiry != (time.Time{}) && payload.Expiry.Before(time.Now()) {
I don't recall we have this requirement? But sure, we can enforce that expiry should always be set for the token.

2024-07-03 07:44 UTC, mas-who commented on internal/api/tokens.go
> +	// TODO: these addresses should be calculated based on configs, extract to util function
Yeah that will be the logic. For point 1, I don't think we will return any member address and just return an array of a single address that is the `global.address` config value.

2024-07-03 07:47 UTC, mas-who commented on internal/api/types/tokens.go
> +type ExternalSiteTokenBody struct {
We can put these outside of the `internal` directory. Although, a project that's importing dependencies from this project will need to do some extra setup since this is a private repo.

2024-07-04 09:26 UTC, edlerd commented on internal/api/types/tokens.go
> +type ExternalSiteTokenBody struct {
Let's ignore the problem for now, I'll put it on our next sync agenda.

2024-07-04 09:29 UTC, edlerd commented on internal/api/tokens.go
> +	if payload.Expiry != (time.Time{}) && payload.Expiry.Before(time.Now()) {
I think we do not want tokens without an expiry date.

2024-07-04 09:31 UTC, edlerd commented on internal/api/tokens.go
> +	// TODO: these addresses should be calculated based on configs, extract to util function
The configured value in 1 should be an array as well, to allow multiple addresses. I agree, it can be an array of 1. But we shouldn't limit it to that.

2024-07-05 14:20 UTC, mas-who commented on cmd/lxd-site-mgrd/main.go
> +	hooks := &config.Hooks{
don't worry about this, I will drop the commit once PR is approved. Keeping this here for now in case if anyone wants to checkout the branch and do some testing

2024-07-05 16:50 UTC, edlerd commented on scripts/create_join_token.sh
> +}' -X POST https://0.0.0.0:9001/1.0/external-site-join-token
```suggestion
}' -X POST https://0.0.0.0:9001/1.0/external-site-join-token
```

2024-07-05 16:50 UTC, edlerd commented on cmd/lxd-site-mgrd/main.go
> +	hooks := &config.Hooks{
I think we need to keep this -- at least the post join hook, no?

2024-07-05 16:50 UTC, edlerd commented on cmd/lxd-site-mgrd/main.go
> +				}
This is better in a script to bootstrap data?

2024-07-05 16:50 UTC, edlerd commented on internal/api/tokens.go
> +
I think this should be moved further down. We don't need to read manager configs in case a globalAddress is found.

2024-07-05 16:50 UTC, edlerd commented on internal/api/tokens.go
> +func getSiteManagerAddresses(s *state.State) ([]string, error) {
I don't think we should filter offline members. We should sort them to the end of the array instead, and put the leader first as now.

Also, can we break this function down so the 1,2,3 steps are obvious by reading the code instead of needing this comment here explaining what the code is doing below? Ideally, the code tells you what it is doing, and the comments tell you why something is done -- which can't be expressed in the code itself.

2024-07-08 07:40 UTC, mas-who commented on cmd/lxd-site-mgrd/main.go
> +	hooks := &config.Hooks{
Yes we do need this hook when the ability to provide configs for network listeners during initialisation is enabled in microcluster. For now, I wouldn't really want to keep this commit for this PR. Soon I will have a PR up for configs CLI, and I plan to write a script using the CLI to initialise the configs just so that we have some dummy data so that the site manager addresses calculation won't break.

2024-07-08 07:41 UTC, mas-who commented on cmd/lxd-site-mgrd/main.go
> +				}
yes I agree, as mentioned in the previous comment, I will setup a script in the configs CLI PR to populate some data.

2024-07-08 07:47 UTC, mas-who commented on internal/api/tokens.go
> +func getSiteManagerAddresses(s *state.State) ([]string, error) {
I don't think there is any value in sending offline member addresses to LXD? This calculation would be performed for every status update eventually so LXD would always get the latest valid addresses. Including offline member addresses means we would need to setup a separate slice to keep track of those addresses then combine them with the valid addresses. This only slightly complicates the logic, but I don't see it being necessary?

I've split out the logic into smaller functions and removed the comments :+1:

2024-07-08 08:02 UTC, edlerd commented on cmd/lxd-site-mgrd/main.go
> +				}
I think the configs already merged, so we can have the script here with some api calls?

2024-07-08 08:04 UTC, edlerd commented on internal/api/tokens.go
> +func getSiteManagerAddresses(s *state.State) ([]string, error) {
The reasoning to include offline members is that they might become online and all other members offline. So it will be beneficial for a cluster to know all possible members, even if they are offline during the time of a status update.

2024-07-08 08:08 UTC, mas-who commented on cmd/lxd-site-mgrd/main.go
> +				}
I was thinking since we will have the CLI ready, might as well write the shell script with the CLI instead of using `curl`?

2024-07-08 08:10 UTC, edlerd commented on cmd/lxd-site-mgrd/main.go
> +				}
Sounds good to me. Then let's keep this on in draft until the CLI is merged and keep the CLI PR focused on adding the feature.

2024-07-08 08:18 UTC, mas-who commented on internal/api/tokens.go
> +func getSiteManagerAddresses(s *state.State) ([]string, error) {
Yeah that's a good point, I've made the change to append offline member address to the end of the site manager addresses slice :+1:

2024-07-08 09:09 UTC, mas-who commented on cmd/lxd-site-mgrd/main.go
> +				}
Here is the CLI [PR](https://github.com/canonical/lxd-site-manager/pull/38) with the config generation script

2024-07-09 09:24 UTC, mas-who commented
@edlerd I have rebased main now that the configs generation script is there. I've marked the PR as non-draft now

2024-07-09 10:11 UTC, edlerd commented on internal/api/tokens.go
> +	return response.SyncResponse(true, encodedToken)
I think this needs to be an object, so we don't send the token directly under the metadata field, but wrapped as a named field. That way, we ensure that we can extend the object later.

2024-07-09 10:11 UTC, edlerd commented on internal/api/tokens.go
> +		})
```suggestion
		responseTokens = append(responseTokens, types.ExternalSiteToken{
			Expiry:   token.Expiry,
			SiteName: token.SiteName,
			CreateAt: token.CreatedAt,
		})
```
Can't this be flattened?

2024-07-09 10:11 UTC, edlerd commented on internal/api/tokens.go
> +	offlineMemberAddresses := make([]string, 0, len(memberConfigs))
There are more states than just online and offline. These are non-online members, not necessarily offline members.

2024-07-09 10:11 UTC, edlerd commented on internal/api/types/tokens.go
> +	ExternalSiteTokenPost
A bit surprised to see the post type included here. I see there is an overlap, though not necessarily a semantic connection.

2024-07-09 11:59 UTC, mas-who commented on internal/api/tokens.go
> +		})
The `ExternalSiteToken` struct type embeds the `ExternalSiteTokenPost` struct type. This is how the syntax works to construct `ExternalSiteToken`, but it does not affect the end result i.e. the json content of the decoded token would be flattened

2024-07-09 12:06 UTC, mas-who commented on internal/api/types/tokens.go
> +	ExternalSiteTokenPost
The intended connection here is that `ExternalSiteToken` represent the data that would be returned from the `GET` endpoint, and it would contain the data from `ExternalSiteTokenPost`

2024-07-09 12:26 UTC, edlerd commented on internal/api/tokens.go
> +		})
This code is a bit unclear, it seems there is a post involved here, but the data is coming entirely from the database. I'd suggest keeping the types independent of each other to avoid making a connection here, where there is none.

2024-07-09 14:16 UTC, edlerd approved these changes
LGTM, thanks for the improvements.

2024-07-09 14:40 UTC, merged