add CLI support for managing manager and member configs [WD-12696]
canonical/microcloud-cluster-manager pull request #38
Opened 2024-07-08 08:04 UTC by mas-who

## Done

- [x] added new CLI command for updating manager or member configs `lxd-site-mgr config set [<member>] key=val...`
- [x] updated `configs` file names to be `manager_configs` for clearer differentiation with `member_configs`
- [x] added new CLI command for showing member configs `lxd-site-mgr config show [<member>]`
- [x] added script for generating dummy configs

2024-07-08 08:04 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-38.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/3988)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-08 16:30 UTC, edlerd commented on cmd/lxd-site-mgr/configs.go
> +			lxd-site-mgr config set global.address=179.0.10.1
We should use some of the ips intended for docs, i.e. 203.0.113.1 as per https://datatracker.ietf.org/doc/html/rfc5737#section-3

2024-07-08 16:30 UTC, edlerd commented on scripts/generate_configs.sh
> +        config set global.address=179.10.10.1
I think this address shouldn't be hard coded?

2024-07-08 16:30 UTC, edlerd commented on scripts/generate_configs.sh
It seems this script has some options and some config comes via env file and some configs are hard coded. I think we should be more strict where things are configured here.

2024-07-09 06:55 UTC, mas-who commented on cmd/lxd-site-mgr/configs.go
> +			lxd-site-mgr config set global.address=179.0.10.1
Interesting, thanks for sharing this

2024-07-09 07:00 UTC, mas-who commented on scripts/generate_configs.sh
Will move everything into `.local.env` file instead since the oidc configs has to be in the env file. That way everything is aligned. If a specific env var isn't defined, then the script will skip generating related configs. This is useful for optional configs such as member `external_address`

2024-07-09 07:34 UTC, edlerd requested changes

2024-07-09 07:34 UTC, edlerd commented on scripts/generate_configs.sh
> +alias lxd-site-mgr='go run ./cmd/lxd-site-mgr'
This doesn't work, I get `scripts/generate_configs.sh: line 24: lxd-site-mgr: command not found`. Let's use the same approach with a `$COMMAND` as in the generate sites script.

2024-07-09 07:48 UTC, edlerd approved these changes
LGTM

2024-07-09 08:04 UTC, merged