feat: Implemented the LXD-SM Settings/Configuration Page [WD-12946]
canonical/microcloud-cluster-manager pull request #46
Opened 2024-07-11 13:42 UTC by Kxiru

- Added Settings Page
- Added Setting table and form
- Added backend api query to both retrieve and patch manager level config settings.

![image](https://github.com/canonical/lxd-site-manager/assets/58699506/198ec994-e4bc-49cb-8de1-c19a488b7d0d)

2024-07-11 13:42 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-46.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/4632)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-11 15:09 UTC, edlerd reviewed
Thank's for adding. I can't see any settings on the demo server. Does this rely on custom configuration to be present?
Can you ensure the config options are available also when the config is at default values?

Edit: i.e. this is the response of the `GET /1.0/config` api call on the demo server:

![image](https://github.com/canonical/lxd-site-manager/assets/1155472/6251222f-860e-4a90-83d0-1889d5c205bf)

2024-07-11 15:12 UTC, edlerd commented on ui/src/pages/Settings.tsx
> +  const configKeys = Object.keys(configOptions?.config || {});
We could have a JSON object with the config options in the repository to rely on here. The API response is not reliable for this, as it will be missing any options with default values.

2024-07-11 15:46 UTC, Kxiru commented
> Thank's for adding. I can't see any settings on the demo server. Does this rely on custom configuration to be present? Can you ensure the config options are available also when the config is at default values?
> 
> Edit: i.e. this is the response of the `GET /1.0/config` api call on the demo server:
> 
> ![image](https://private-user-images.githubusercontent.com/1155472/347877442-6251222f-860e-4a90-83d0-1889d5c205bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MTI2MzEsIm5iZiI6MTcyMDcxMjMzMSwicGF0aCI6Ii8xMTU1NDcyLzM0Nzg3NzQ0Mi02MjUxMjIyZi04NjBlLTRhOTAtODNkMC0xODg5ZDVjMjA1YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTUzODUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjE3MjcxMzY5ZGFkOWE0ZjlmZDZjY2UxYzVmYmM3MThiYzBjYjYwM2UxODE4OTczYTY3OTFkYmI2Mjk0Zjk3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B3W4dCMNL_F9PFuo919xQa42PpTkOeprO4k1tcpVw2w)

Yes, I have sent some information that will address this in Mattermost. That being said, I believe @mas-who is creating a PR to address this.

2024-07-11 15:49 UTC, Kxiru commented on ui/src/pages/Settings.tsx
> +  const configKeys = Object.keys(configOptions?.config || {});
Apologies, I am not sure I understand. Please could you clarify what you mean?

2024-07-11 16:28 UTC, edlerd commented on ui/src/pages/Settings.tsx
> +  const configKeys = Object.keys(configOptions?.config || {});
The configOptions can be empty and we will render an empty settings page as in the demo server. So instead of relying on the options from the api response, we can have the list hardcoded in the frontend, to ensure they are available in the settings page independent of the current configuration.

2024-07-11 16:33 UTC, Kxiru commented on ui/src/pages/Settings.tsx
> +  const configKeys = Object.keys(configOptions?.config || {});
Ooh, okay sure, can do!

2024-07-12 12:55 UTC, mas-who commented
@Kxiru can you also add `"ui/settings"` to `uiServeRoutes` in `internal/api/ui.go` file?

Edit: currently if you try do a browser refresh while on the settings page, it will result in a 404 not found error from the backend because the path isn't added, this should be documented and I have planned a task for this next pulse

2024-07-12 13:07 UTC, edlerd requested changes
Seems to work fine now, some comments below.

2024-07-12 13:07 UTC, edlerd commented on ui/src/App.tsx
> +        <Route path="/ui/settings" element={<Settings />} />
This needs to be added to the `uiServeRoutes` in `ui.go` as well. So we can refresh / land directly on this URL.

2024-07-12 13:07 UTC, edlerd commented on ui/package.json
> +    "backend-init": "cd .. &&  go run ./cmd/lxd-site-mgr --state-dir ./state/dir1/ waitready && go run ./cmd/lxd-site-mgr --state-dir ./state/dir1/ init \"member1\" 0.0.0.0:9001 --bootstrap && script
I think this shouldn't be changed, or is there a reason for it?

2024-07-12 13:07 UTC, edlerd commented on ui/src/components/Animate.tsx
This seems unused, can it be removed?

2024-07-12 13:07 UTC, edlerd commented on ui/src/pages/Settings.tsx
> +    "global.address": "0.0.0.0:8414",
This should be called defaultConfig and the values should all be empty string.

2024-07-12 13:07 UTC, edlerd commented on ui/src/pages/Settings.tsx
> +  // const configKeys = Object.keys(configOptions?.config || {});
```suggestion
```

2024-07-12 13:07 UTC, edlerd commented on ui/src/pages/settings/SettingForm.tsx
> +};
This function should not be exported and live next to the file it is used in.

2024-07-12 13:07 UTC, edlerd commented on ui/src/util/notifications.tsx
This seems unused, can it be removed?

2024-07-12 14:13 UTC, Kxiru commented on ui/package.json
> +    "backend-init": "cd .. &&  go run ./cmd/lxd-site-mgr --state-dir ./state/dir1/ waitready && go run ./cmd/lxd-site-mgr --state-dir ./state/dir1/ init \"member1\" 0.0.0.0:9001 --bootstrap && script
Supposedly for the configs to be able to be edited in the demo server, the initial configs should not be generated. @mas-who , could you perhaps offer some clarification, here?

2024-07-12 16:00 UTC, edlerd approved these changes
LGTM, thanks for adding and improving the new config page.

2024-07-12 16:06 UTC, merged