preparation for network listener update in microcluster [WD-13102]
canonical/microcloud-cluster-manager pull request #47
Opened 2024-07-11 13:53 UTC by mas-who

## Done

- [x] setup control listener to listen on different address than core listener
- [x] moved `POST /1.0/sites` endpoint to control listener
- [x] initialise control listener in `PostBootstrap` and `PostJoin` hooks. In addition, the initialisation will add a entry in the `manager_member_configs` table for each member with `https_address` populated. This also means we can remove logic populating `https_address` in the `generate_configs.sh` script.
- [x] setup global site manager state to hold `microcluster.Microcluster`. We pass this state into some endpoints so we can access client functions e.g. for updating network listener addresses
- [x] updated `PATCH /1.0/member/{name}/config` endpoint so that we will forward the request to the correct member if `https_address` is present in the payload. We will still populate the data inside dqlite so that read operations will be much easier to handle (trading off with some data redundancy)
- [x] to ensure config data is synced between daemon local config and dqlite, added a revert function to rollback a network listener update if the corresponding db transaction fails

## Context
 - This PR is created in preparation for the microcluster [update](https://github.com/canonical/microcluster/pull/174) that allows modification to network listeners.
 - **Currently this PR won't work since dependencies are not yet updated.**

## Follow up task
 - cache control listener and external addresses in the daemon state. This will improve efficiency for status updates.

## Testing
 - setup cluster with multiple members
 - update `https_address` config for individual members with `lxd-site-mgr config set <member> https_address=<address>`. 
 - make sure it works exactly as before.
 - @edlerd it would be great if you can test the join process since `POST /1.0/sites` is on a different listener now. I've tested it locally already but I think it would be good if you can check it too.

2024-07-11 13:53 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-47.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/4638)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-11 13:58 UTC, mas-who commented on go.mod
> +replace github.com/canonical/microcluster => ../microcluster
this will be removed after upstream merge

2024-07-12 04:54 UTC, mas-who commented
@edlerd @roosterfish this is now ready for review with upstream [PR](https://github.com/canonical/microcluster/pull/174) merged.

2024-07-12 08:05 UTC, roosterfish reviewed
Looks great, nice to see that you have added the `revert` pattern.

2024-07-12 08:05 UTC, roosterfish commented on internal/api/server.go
> +		string(ManagementListener): siteManagementListener,
I am wondering if we should make this a non `string` type already on microcluster side?
Because there are two specific server names `core` and `unix` which are special and cannot be set (you will get an error). 
Having a type with already defined constants might make it easier to reason about this restriction.

2024-07-12 08:15 UTC, mas-who commented on internal/api/server.go
> +		string(ManagementListener): siteManagementListener,
Yes I think that makes sense! It will highlight there are restrictions to server names that we can set.

2024-07-12 12:51 UTC, mas-who commented
got a but in microcluster that would non-deterministically cause conflicting endpoint errors. Here is the fix for it https://github.com/canonical/microcluster/pull/180. Before that gets merged, we should not merge this PR since the build process may fail non-deterministically

2024-07-16 07:08 UTC, mas-who commented on internal/api/server.go
> +		string(ManagementListener): siteManagementListener,
created an [issue](https://github.com/canonical/microcluster/issues/184) for this.

2024-07-16 08:02 UTC, edlerd requested changes

2024-07-16 08:02 UTC, edlerd commented on internal/api/sites.go
> +}
I think we should split the control listener endpoints and the public ones into dedicated files. Keeping the code in one file is a bit of a trap for the future.

2024-07-16 08:02 UTC, edlerd commented on internal/api/server.go
> +func siteManagementListener(s *state.SiteManagerState) rest.Server {
```suggestion
func publicListener(s *state.SiteManagerState) rest.Server {
```
Better name?

2024-07-16 08:02 UTC, edlerd commented on internal/api/server.go
Should we split this to have a dedicated file for each listener server?

2024-07-16 08:02 UTC, edlerd commented on internal/api/types/server.go
> +	// InternalEndpoint - all endpoints restricted to trusted servers.
```suggestion
	// InternalEndpoint is restricted to trusted servers.
```

2024-07-16 08:51 UTC, mas-who commented on internal/api/sites.go
> +}
great idea! I've split the endpoints into `sites_management.go` and `sites_control.go`

2024-07-16 08:52 UTC, mas-who commented on internal/api/server.go
> +func siteManagementListener(s *state.SiteManagerState) rest.Server {
I would keep the naming consistent with the spec, should we update the spec to align the naming as well?

2024-07-16 08:54 UTC, mas-who commented on internal/api/server.go
I think there aren't that many endpoints to make the file difficult to manage. Splitting listeners into separate files in this case seems to be a bit of an overkill and would only introduce unnecessary folder structure imo

2024-07-16 08:56 UTC, edlerd commented on internal/api/server.go
> +func siteManagementListener(s *state.SiteManagerState) rest.Server {
I am not too opinionated on this change. Wdyt? If we change it, we should keep the spec updated, yes.

2024-07-16 08:59 UTC, mas-who commented on internal/api/server.go
> +func siteManagementListener(s *state.SiteManagerState) rest.Server {
let's keep it as is for now then. I think given we will most likely change `site` to `cluster` or something else, we might end up changing the listener names as well eventually. Updating this now may be a little premature

2024-07-16 09:38 UTC, edlerd requested changes
demo build is failing due to the missing version.

![image](https://github.com/user-attachments/assets/3b9d8b02-7b5f-4f81-a57b-1134a511171e)

2024-07-16 09:44 UTC, mas-who commented
> demo build is failing due to the missing version.
> 
> ![image](https://private-user-images.githubusercontent.com/1155472/349029561-3b9d8b02-7b5f-4f81-a57b-1134a511171e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjMzMDAsIm5iZiI6MTcyMTEyMzAwMCwicGF0aCI6Ii8xMTU1NDcyLzM0OTAyOTU2MS0zYjlkOGIwMi03YjVmLTRmODEtYTU3Yi0xMTM0YTUxMTE3MWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDk0MzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIyMjcyZDUzOThhODY4ZTczOTU5MTFiMjI2OWQ4ZDg2MDc4OTViNTQ1ZTIwMGM3NGM0MTViZTczNDhmMWVlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c34pxdXfOFgGXEkExtMR4pinpKaMX7tisWYtgNWVdv8)

Interesting, will look into it. The version is set in the `make` target so something is wrong with the version environment variable setup.

2024-07-16 10:38 UTC, edlerd approved these changes
LGTM, thanks.

2024-07-16 11:14 UTC, merged