[WD-13151] chore: split last seen column into "Status" and "Last Heartbeat" colu…
canonical/microcloud-cluster-manager pull request #48
Opened 2024-07-15 11:27 UTC by Kxiru

…mns.

Work done:
- Split columns into "Status" and "Last Heartbeat"
- Altered Heartbeat logic to display last seen times differently.
- Created a new ClusterStatus Component.
- Moved Cluster metrics into dedicated cluster_metrics folder.
- Changed Site Generation last-seen attribute to generate random times within the last 30 minutes for visualisation purposes.

![image](https://github.com/user-attachments/assets/1f395ba4-41f7-451c-afe4-c90bdf81f3f4)

2024-07-15 11:27 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-48.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/5133)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-16 06:00 UTC, edlerd requested changes
QA lgtm, two small ideas to simplify the structure.

2024-07-16 06:00 UTC, edlerd commented on ui/src/pages/clusters/ClusterList.tsx
> +import { ClusterInstances } from "components/cluster_metrics/ClusterInstances";
```suggestion
import { ClusterInstances } from "./metrics/ClusterInstances";
```
Let's keep those under the pages/clusters/metrics folder. That way they have a shorter and more concise path and are easier to find. Components is meant for generic ones, which are not tied to any dedicated page / functionality.

2024-07-16 06:00 UTC, edlerd commented on ui/src/util/helpers.tsx
> +  return returnArray;
I think this function is doing too many things. Maybe we refactor it to return the `lastHeartbeatMins`. The logic to figure out the copy for `ClusterHeartbeat` can be local to that component. And the logic to calculate the status / icon can be local to the `ClusterStatus` component.

2024-07-16 12:52 UTC, Kxiru commented on ui/src/util/helpers.tsx
> +  return returnArray;
Thanks, for the review, David. All done!

2024-07-16 13:24 UTC, edlerd commented on ui/src/pages/clusters/metrics/ClusterStatus.tsx
> +      {lastHeartbeatMins ? "Online" : "Offline"}
```suggestion
      {lastHeartbeatMins < 5 ? "Online" : "Offline"}
```

2024-07-16 13:24 UTC, edlerd commented on ui/src/util/helpers.tsx
> +export function getHeartbeatStatus(cluster: Cluster): number {
```suggestion
export function getMinuesSinceLastHeartbeat(cluster: Cluster): number {
```

2024-07-16 13:24 UTC, edlerd commented on ui/src/util/helpers.tsx
> +  const lastHeartbeatMins = Math.floor((Date.now() - lastSeenTime) / 60000);
```suggestion
  return Math.floor((Date.now() - lastSeenTime) / 60000);
```

2024-07-16 13:24 UTC, edlerd commented on ui/src/pages/clusters/metrics/ClusterStatus.tsx
> +      {lastHeartbeatMins ? "Online" : "Offline"}
I think this is missing a comparison.

2024-07-16 13:24 UTC, edlerd commented on ui/src/util/helpers.tsx
> +export function getHeartbeatStatus(cluster: Cluster): number {
More precise?

2024-07-16 13:24 UTC, edlerd commented on ui/src/util/helpers.tsx
> +  const lastHeartbeatMins = Math.floor((Date.now() - lastSeenTime) / 60000);
Can simplify a bit.

2024-07-16 14:39 UTC, edlerd submitted a review, later dismissed
LGTM :+1:

2024-07-16 15:04 UTC, edlerd approved these changes

2024-07-16 15:10 UTC, merged