cli for generating external site join token [WD-13155]
canonical/microcloud-cluster-manager pull request #49
Opened 2024-07-15 13:30 UTC by mas-who

## Done
 - added CLI for generating external site join token

## QA
 - try `go run ./cmd/lxd-site-mgr --state-dir state/dir1 external-site-join-tokens add <site_name> [--expiry=duration]`
 - try `go run ./cmd/lxd-site-mgr --state-dir state/dir1 external-site-join-tokens show`
 - try `go run ./cmd/lxd-site-mgr --state-dir state/dir1 external-site-join-tokens revoke <site_name>`

2024-07-15 13:30 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-49.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/5159)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-17 09:53 UTC, edlerd commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +		Use:   "add <site_name>",
Are we missing the expiry option here?

2024-07-17 09:53 UTC, edlerd commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +}
Should this be called `delete` instead of `revoke`?

2024-07-17 09:53 UTC, edlerd commented on scripts/generate_site_join_token.sh
> +$COMMAND --state-dir ./state/dir1 external-site-join-tokens add site1 -e 24h
```suggestion
$COMMAND --state-dir ./state/dir1 external-site-join-tokens add site1 -e 24h

```

2024-07-17 09:53 UTC, edlerd commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +	cmd.Flags().DurationVarP(&c.flagExpiry, "expiry", "e", 0, "Specify the duration (i.e. ns, us, ms, s, m or h) for the token to be valid")
Not sure if `e` is a good shorthand, it might be ambiguous. Can we have no short version and only the long one?

2024-07-17 11:11 UTC, mas-who commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +		Use:   "add <site_name>",
the flag is registered by `cmd.Flags()` down below. Do you mean we should add it to the example usage? There is help text for the flag already, but I can add it to the example if needed.

2024-07-17 11:16 UTC, mas-who commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +}
I think it's probably better to keep the command consistent with lxd token related cli commands. So `revoke` instead of `delete`. I think to the user `revoke` also makes sense since `delete` is more of an operation we do at the database level

2024-07-17 15:33 UTC, edlerd commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +		Use:   "add <site_name>",
I thought the Usage example also show optional flags within square brackets.

2024-07-17 17:10 UTC, mas-who commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +		Use:   "add <site_name>",
This is the Usage for `lxc list`

![Screenshot from 2024-07-17 19-08-15](https://github.com/user-attachments/assets/d5989bf6-56b7-4dd3-90f7-bbe60b015822)

The `[flags]` in the usage only references the Flags section. I don't think all the flags would show up in the usage or usage examples section?

2024-07-17 17:13 UTC, mas-who commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +		Use:   "add <site_name>",
![Screenshot from 2024-07-17 19-13-23](https://github.com/user-attachments/assets/ff2a718c-88ce-403c-8733-67a6d10cf0de)

2024-07-17 18:37 UTC, edlerd commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +		Use:   "add <site_name>",
This looks good, I was confused 🤔 over the flags not being mentioned before in the help at all. Makes much sense this way 👍

2024-07-18 07:26 UTC, mas-who commented
Thanks for the review @edlerd on this one. Do you have any additional comments before approving?

2024-07-18 07:27 UTC, mas-who commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +		Use:   "add <site_name>",
Yeah thanks for bringing it up. It's good that we checked this to make sure behaviour aligns with LXD :slightly_smiling_face:

2024-07-18 10:07 UTC, edlerd requested changes
QA looks fine, but the add command should surface the token to the user. We should never show the secret or the token again after creation. So maybe show the token in the cli output together with a note to store it as it will not be possible to retrieve the token value again.

2024-07-18 10:07 UTC, edlerd commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +}
This should print a response with the token to the cli.

2024-07-18 10:51 UTC, mas-who commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +}
yes of course, this is done. We should definitely do that in the UI as well, will leave a comment in the Jira task.

![Screenshot from 2024-07-18 12-47-03](https://github.com/user-attachments/assets/e7b74791-426c-4236-9eff-23601e389821)

2024-07-18 11:45 UTC, edlerd commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +}
Looks good in the screenshot. Can you push the fix for this or is this still pending further tests?

2024-07-18 11:47 UTC, mas-who commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +}
oops forgot to push, done

2024-07-18 12:29 UTC, edlerd requested changes

2024-07-18 12:29 UTC, edlerd commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +		Use:   "external-site-join-tokens",
```suggestion
		Use:   "external-site-join-token",
```
I think for consistency this should be singular

2024-07-18 12:29 UTC, edlerd commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +	fmt.Printf("%s", data)
I think tabular output like with `site list` is beneficial here.

2024-07-18 12:51 UTC, mas-who commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +	fmt.Printf("%s", data)
100%

2024-07-18 13:28 UTC, edlerd submitted a review, later dismissed
LGTM, one more idea to improve the inline help a bit, also ready to merge as is.

2024-07-18 13:28 UTC, edlerd commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +	cmd.Flags().DurationVar(&c.flagExpiry, "expiry", 0, "Specify the duration (i.e. ns, us, ms, s, m or h) for the token to be valid")
```suggestion
	cmd.Flags().DurationVar(&c.flagExpiry, "expiry", 0, "Specify the duration (i.e. 5m or 48h) for the token to be valid")
```
Probably better to avoid the small units here and give more reasonable examples?

2024-07-18 14:25 UTC, mas-who commented on cmd/lxd-site-mgr/external_site_join_tokens.go
> +	cmd.Flags().DurationVar(&c.flagExpiry, "expiry", 0, "Specify the duration (i.e. ns, us, ms, s, m or h) for the token to be valid")
thanks, updated as per suggestion :)

2024-07-18 14:54 UTC, mas-who commented
@edlerd I think this one is ready for approval :)

2024-07-18 15:28 UTC, edlerd approved these changes
LGTM, thanks for the iterations!

2024-07-18 15:30 UTC, merged