tests: visual regression for checking logo asset [WD-13063]
canonical/microcloud-cluster-manager pull request #50
Opened 2024-07-15 13:33 UTC by mas-who

## Done
 - visual regression test for logo asset

2024-07-15 13:33 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-50.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/5160)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-16 06:52 UTC, edlerd requested changes

2024-07-16 06:52 UTC, edlerd commented on ui/package.json
> +    "test-e2e-screenshots": "npx playwright test --update-snapshots"
```suggestion
    "test-e2e-update": "npx playwright test --update-snapshots"
```
Maybe clearer?

2024-07-16 06:52 UTC, edlerd commented on ui/tests/screenshot/logo.spec.ts-snapshots/logo-screenshot-1-chromium-linux.png
Can we change this to have the same assets for chromium and firefox?

2024-07-16 07:34 UTC, mas-who commented on ui/tests/screenshot/logo.spec.ts-snapshots/logo-screenshot-1-chromium-linux.png
done :+1:

2024-07-16 07:43 UTC, edlerd approved these changes
Code LGTM, test needs changes to become green though.

2024-07-16 07:47 UTC, mas-who commented
@edlerd so looking at the CI failure, the chromium logo test is failing with a 7% pixel difference when compared to the screenshot. This is probably due to the screenshot being taken in firefox. Looking at the screenshots comparison, it almost feels like there is some kind of colour difference between firefox and chrome? Not sure if using the same screenshot for cross platform projects may result in these small differences all the time. We could try fix the pixel difference somehow, set a threshold for pixel difference in testing or go back to per project screenshots. wdyt? 

![900b5bcc611bb6742af2ea338d68c11f2800f537](https://github.com/user-attachments/assets/7b7e9dd7-991d-42ba-af44-0ae06ea0a041)
![62e3a0a6dd73ce2473cd1f18083874bef96aced2](https://github.com/user-attachments/assets/623701e0-c480-4cc3-9e1b-0fd4c036ec85)
![176ac2a1ffc9e9c733b4c54dcc629face4dd9a13](https://github.com/user-attachments/assets/84abed95-f1fe-4ad5-9705-3a745ddd670e)

2024-07-16 07:50 UTC, edlerd commented
> @edlerd so looking at the CI failure, the chromium logo test is failing with a 7% pixel difference when compared to the screenshot. This is probably due to the screenshot being taken in firefox. Looking at the screenshots comparison, it almost feels like there is some kind of colour difference between firefox and chrome? Not sure if using the same screenshot for cross platform projects may result in these small differences all the time. We could try fix the pixel difference somehow, set a threshold for pixel difference in testing or go back to per project screenshots. wdyt?

I see, thanks for figuring this out. Maybe easier in that case to revert to the previous case of having dedicated screenshots for each browser?

2024-07-16 08:03 UTC, edlerd approved these changes
LGTM, thanks for adding and figuring out the snapshot diff.

2024-07-16 08:12 UTC, merged