feat: [WD-13154] add Pending and Token tabs to the Clusters Page.
canonical/microcloud-cluster-manager pull request #51
Opened 2024-07-15 17:15 UTC by Kxiru

Work Done:
- Created individual tables for Active and Pending clusters.
- Added a Token Table
- Added an API function to fetch Tokens
- Filtered clusters by status
- Added Token generation script to backend-init.
- Added "Add New Cluster" button.

![image](https://github.com/user-attachments/assets/522b25bf-c6bf-44dc-8b0c-051d22186ab7)

![image](https://github.com/user-attachments/assets/09a9e257-ef31-4851-95cd-4af98c4ceb69)

![image](https://github.com/user-attachments/assets/74807f21-05e9-418a-b6bb-3d00260eacc5)

2024-07-15 17:15 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-51.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/5210)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-16 06:27 UTC, edlerd requested changes
This is on a good track, the token needs a fix for catering the empty case. I think we need the same fix on the api level to fall back to empty array also for the function loading clusters. Some suggestions as well.

2024-07-16 06:27 UTC, edlerd commented on internal/api/ui.go
> +	"ui/sites/active",
```suggestion
```
The active routes is `ui/sites`. Also better to keep this array sorted.

2024-07-16 06:27 UTC, edlerd commented on ui/src/App.tsx
> +const ClusterList = lazy(() => import("pages/ClusterList"));
```suggestion
const ClusterList = lazy(() => import("pages/clusters/ClusterList"));
```
Better keep this in the module it belongs to.

2024-07-16 06:27 UTC, edlerd commented on ui/src/pages/ClusterList.tsx
> +        <TabLinks tabs={tabs} activeTab={activeTab} tabUrl={`/ui/sites`} />
```suggestion
        <TabLinks tabs={tabs} activeTab={activeTab} tabUrl="/ui/sites" />
```

2024-07-16 06:27 UTC, edlerd commented on ui/src/pages/ClusterList.tsx
> +          {!activeTab && <ClusterListActiveTable />}
```suggestion
          {!activeTab && <ClusterListActive />}
```
I think we can drop the table suffix from all three components?

2024-07-16 06:27 UTC, edlerd commented on ui/src/pages/clusters/ClusterListPendingTable.tsx
> +        { content: `${cluster.joined_at}` },
```suggestion
        { content: `${isoTimeToString(cluster.joined_at)}` },
```
we can use the `isoTimeToString` function from lxd-ui here.

2024-07-16 06:27 UTC, edlerd commented on ui/src/api/clusters.ts
> +      .then((data: LxdApiResponse<Token[]>) => resolve(data.metadata))
```suggestion
      .then((data: LxdApiResponse<Token[]>) => resolve(data.metadata ?? []))
```
This could be null, and we have to ensure it to be array here to prevent problems further down in the useage.

2024-07-16 06:27 UTC, edlerd commented on ui/src/api/clusters.ts
> +    fetch("/1.0/external-site-join-token")
This is better split into a dedicated file matching the api path.

2024-07-16 06:27 UTC, edlerd commented on ui/src/pages/clusters/ClusterListTokensTable.tsx
> +          content: `${token.expiry}`,
```suggestion
          content: `${isoTimeToString(token.expiry)}`,
```

2024-07-16 06:27 UTC, edlerd commented on ui/src/pages/clusters/ClusterListTokensTable.tsx
> +          content: `${token.created_at}`,
```suggestion
          content: `${isoTimeToString(token.created_at)}`,
```

2024-07-16 06:27 UTC, edlerd commented on ui/src/pages/clusters/ClusterListTokensTable.tsx
> +      aria-labelledby="Active"
```suggestion
      aria-labelledby="Tokens"
```

2024-07-16 06:27 UTC, edlerd commented on ui/src/pages/clusters/ClusterListTokensTable.tsx
> +              <>No token found matching this search</>
```suggestion
              <>No tokens found.</>
```

2024-07-16 06:27 UTC, edlerd commented on ui/src/pages/clusters/ClusterListPendingTable.tsx
> +      aria-labelledby="Active"
```suggestion
      aria-labelledby="Pending"
```

2024-07-16 06:27 UTC, edlerd commented on ui/src/pages/clusters/ClusterListPendingTable.tsx
> +              <>No cluster found matching this search</>
```suggestion
              <>No pending clusters.</>
```

2024-07-16 12:57 UTC, Kxiru commented on ui/src/pages/clusters/ClusterListPendingTable.tsx
> +        { content: `${cluster.joined_at}` },
This is a great tool, thanks. I'll use it here and in the other relevant columns in the other tables.

2024-07-16 13:30 UTC, edlerd requested changes

2024-07-16 13:30 UTC, edlerd commented on internal/api/ui.go
> +	"ui/sites",
We should add the new routes.

2024-07-16 13:30 UTC, edlerd commented on ui/src/pages/clusters/ClusterList.tsx
> +import ClusterListPendingTable from "./ClusterListPending";
Best remove the table suffix from the local import name as well.

2024-07-16 13:30 UTC, edlerd commented on ui/src/pages/clusters/ClusterListActive.tsx
> +const ClusterListActiveTable: FC = () => {
```suggestion
const ClusterListActive: FC = () => {
```
Best clean up also the other component names.

2024-07-16 13:30 UTC, edlerd commented on ui/src/pages/clusters/PendingClusterActions.tsx
> +    </div>
Can you add a button and API call for the approval?

2024-07-16 14:26 UTC, Kxiru commented on ui/src/pages/clusters/PendingClusterActions.tsx
> +    </div>
All done!

2024-07-16 14:34 UTC, edlerd reviewed
LGTM, thanks for adding and improving.

2024-07-16 14:35 UTC, edlerd approved these changes

2024-07-16 14:42 UTC, merged