ui: add member configs to settings page [WD-12947]
canonical/microcloud-cluster-manager pull request #53
Opened 2024-07-16 19:11 UTC by mas-who

## Done
- Added member configs to settings page
- Allow reset external address for members
- Use correct client for updating member configs. Previously a bug was introduced where we'd use a local client to get a remote member's server configs for updating the same entry in the database.

## Context
With #47 merged, it is now guaranteed that every member in the cluster will have configs in the `manager_member_configs` table during initialisation. So member configs will show in the settings page by default with its `https_address` setting.

2024-07-16 19:11 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-53.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/5433)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-17 08:54 UTC, edlerd commented on ui/src/pages/Settings.tsx
> +            content: <div className="key-cell">{key}</div>,
There is a problem as we hide the "scope" column on mobile and it contains important info on which member the config belongs to. Maybe use the member name as a prefix to the key? So it is `member.foo.bar`.

2024-07-17 09:52 UTC, Kxiru reviewed
LGTM! Thanks for also renaming the old configs to ManagerConfigs throughout the codebase.

2024-07-17 09:57 UTC, edlerd commented on ui/src/pages/Settings.tsx
> +                  {index === 0 ? memberConfig.target : ""}
Should we make this a bit more consistent with the "Cluster" scope above? Maybe "Member (:member-name)" or alike? We also need to be careful as the member name is user provided, so it might be very long, and it shouldn't break the ui in that case.

2024-07-17 10:57 UTC, mas-who commented on ui/src/pages/Settings.tsx
> +                  {index === 0 ? memberConfig.target : ""}
Yeah that sounds good. I think text overflow elipses with a title attribute should be good. For both the Scope column and the Key column

2024-07-17 15:32 UTC, edlerd commented on internal/api/member_configs.go
> +		if payload.ExternalAddress != nil && *payload.ExternalAddress != "" {
Why using a pointer here, but not on the other checks left and above?

2024-07-17 15:32 UTC, edlerd commented on internal/api/types/member_configs.go
> +	ExternalAddress *string `json:"external_address,omitempty"`
I think none of those should be pointers

2024-07-17 15:32 UTC, edlerd commented on ui/src/pages/Settings.tsx
> +                      key as keyof typeof defaultMemberConfigs
Can these casts be removed if we type `defaultMemberConfigs` in relation to MemberOptions?

2024-07-17 15:32 UTC, edlerd commented on ui/src/pages/settings/SettingForm.tsx
> +      : updateManagerConfigs(config)
We need to display the errors and probably also should have success notifications.

2024-07-17 16:49 UTC, mas-who commented on internal/api/member_configs.go
> +		if payload.ExternalAddress != nil && *payload.ExternalAddress != "" {
resolving this comment as the next one is related.

2024-07-17 16:49 UTC, mas-who commented on internal/api/types/member_configs.go
> +	ExternalAddress *string `json:"external_address,omitempty"`
as discussed, we will convert the payload to a config map and check if keys exist to avoid using pointers.

2024-07-17 17:00 UTC, mas-who commented on ui/src/pages/Settings.tsx
> +                      key as keyof typeof defaultMemberConfigs
yes and done :+1:

2024-07-17 17:02 UTC, mas-who commented on ui/src/pages/settings/SettingForm.tsx
> +      : updateManagerConfigs(config)
Yes but I think we already have a separate task planned to bring notification into site manager across the app?

2024-07-18 09:34 UTC, mas-who commented on internal/api/types/member_configs.go
> +	ExternalAddress *string `json:"external_address,omitempty"`
@edlerd I've done the changes as discussed and updated the spec for this.

2024-07-18 11:56 UTC, edlerd requested changes

2024-07-18 11:56 UTC, edlerd commented on internal/api/api.go
> +
This is dangerous. Allows to bypass any auth in case a header is set. Probably not something we should do.

2024-07-18 11:56 UTC, edlerd commented on internal/api/types/member_configs.go
> +}
I think we can go with a more lean approach: Not validate at all, to save a couple lines and any unknown config keys will be not handled / ignored.

2024-07-18 11:56 UTC, edlerd commented on ui/src/api/settings.ts
> +};
When I click "Save" this is executed twice. It could also reproduce it in lxd-ui. I suspect there is something wrong with the form submission. If you find a fix, can you also open a PR on lxd-ui please?

2024-07-18 11:56 UTC, edlerd commented on ui/src/pages/settings/SettingForm.tsx
> +      : updateManagerConfigs(config)
Sounds good to me.

2024-07-18 12:58 UTC, mas-who commented on internal/api/api.go
> +
This is needed since we need to forward a request to the specific member that requires config update. However, a cluster client will not have oidc cookies and will fail the auth check here. I think here if we check for the header, and that the request host is a valid member address in the cluster, then it should be sufficient wdyt?

2024-07-18 12:59 UTC, mas-who commented on internal/api/api.go
> +
also this check can happen only if a request fails the oidc auth check

2024-07-18 14:18 UTC, mas-who commented on internal/api/api.go
> +
actually, a better check here is to see if a forwarded request has a trusted cert

2024-07-18 14:22 UTC, mas-who commented on internal/api/types/member_configs.go
> +}
yeah true, since we already validating if both `https_address` and `external_address` are missing, there is no need to do this validation. Will remove.

2024-07-18 14:33 UTC, mas-who commented on ui/src/api/settings.ts
> +};
It's because in `SettingFormInput` we invoke the `onSubmit` prop for both form submission and on clicking the save button. Take out `onClick` for the save button and set its `type` attribute to `submit` fixes the issue. Will make a PR in lxd-ui as well.

2024-07-18 16:28 UTC, edlerd approved these changes

2024-07-18 16:28 UTC, edlerd approved these changes
LGTM, I could see a newly set external address in a created join token :+1:

2024-07-18 17:00 UTC, mas-who commented
> LGTM, I could see a newly set external address in a created join token 👍

Nice, thanks for checking that! :slightly_smiling_face:

2024-07-18 17:01 UTC, merged