Add api endpoint and cli for editing site data [WD-13156]
canonical/microcloud-cluster-manager pull request #54
Opened 2024-07-17 08:28 UTC by mas-who

## Done
 - added api endpoint `PATCH /1.0/sites/{siteName}` for updating `site_details` data
 - added cli for editing site data i.e. `go run ./cmd/lxd-site-mgr --state-dir state/dir1 site edit <site_name> [flags]`

2024-07-17 08:28 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-54.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/5512)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-17 09:48 UTC, edlerd requested changes

2024-07-17 09:48 UTC, edlerd commented on internal/api/sites_management.go
> +		Path: "sites/{siteName}/approve",
We missed this in the spec, but I think the endpoint should be `POST /1.0/sites/:name` with a payload of `{status: active}`.
We don't need a dedicated endpoint for approval. A generic POST to modify a site should be fine.

2024-07-17 09:57 UTC, mas-who commented on internal/api/sites_management.go
> +		Path: "sites/{siteName}/approve",
yea sounds good :+1: I think we had this endpoint previously because it would modify mutliple table resources e.g. add site details then delete tokens. But we moved away from that approach so this makes sense

2024-07-17 10:51 UTC, mas-who commented on internal/api/sites_management.go
> +		Path: "sites/{siteName}/approve",
made the change. I think the endpoint should be `PATCH` and not `POST` since we are updating configs. Will update the spec once this PR is finalised.

2024-07-17 15:20 UTC, edlerd commented on internal/api/sites_control.go
> +	payload := types.SiteJoinPost{}
I think this shouldn't be renamed.

2024-07-17 15:20 UTC, edlerd commented on cmd/lxd-site-mgr/sites.go
> +		Use:   "approve-join <site_name>",
Should this be `site edit <site_name>` with passing optional flags for setting the status?

2024-07-17 17:19 UTC, mas-who commented on cmd/lxd-site-mgr/sites.go
> +		Use:   "approve-join <site_name>",
I think introducing a cli command like this one means we should also make the patch endpoint to allow editing all relevant site detail fields. Not sure if it's a little too early to be so generic?

2024-07-17 18:40 UTC, edlerd commented on cmd/lxd-site-mgr/sites.go
> +		Use:   "approve-join <site_name>",
I'd be fine to limit the cli to changing status only for now. My concern was to avoid the very specific cli for approving, where we could have a more generic one that can be extended later.

2024-07-18 08:02 UTC, mas-who commented
I've updated the [spec](https://docs.google.com/document/d/1q0mlkekLO7iTVnktHFJU2VTGAE9ojtR7av1N3QHZGo8/edit) removing the `POST /1.0/sites/:name/approve` endpoint and added the `PATCH /1.0/sites/:name` endpoint with the `SitePatch` payload struct.

2024-07-18 08:04 UTC, edlerd approved these changes
LGTM :+1:

2024-07-18 09:34 UTC, merged