feat: [WD-13149] Implement Cluster Status Graph Summary
canonical/microcloud-cluster-manager pull request #57
Opened 2024-07-18 21:39 UTC by Kxiru

Work done:
- Implemented Bar chart from Maas with some minor amendments to fit our use case.
- Appropriately destructured the ClusterList Graph Bar and relevant sub-components.
- Added and amended scss.
- Implemented logic to display the percentage breakdowns of active, pending and "degraded" states. More clarification on the appropriate states to include in the doughnut will be useful. Additionally replaced the NanoID dependency with a new ChartID prop for memoization.

![image](https://github.com/user-attachments/assets/797d55ea-c63d-4657-b5a7-7b9f443a6385)

Notes:
- The Doughnut chart component could be upstreamed to React Components.

2024-07-18 21:39 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-57.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/5871)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-19 08:53 UTC, edlerd requested changes
Visually looks great! Please try to avoid introducing custom CSS. Where possible, use the existing components as building blocks. Some ideas to simplify and for more semantic HTML below.

2024-07-19 08:53 UTC, edlerd commented on ui/src/pages/clusters/metrics/ClusterStatusGraph.tsx
> +        <h5>{totalClusters} clusters</h5>
h5 seems semantically wrong. The heading should be consecutive h1 > h2 > h3, etc. We seem to be skipping a few levels. For styling you can use the `p-heading--5` class

2024-07-19 08:53 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +    margin: 0;
You can use the `u-no-margin` class instead

2024-07-19 08:53 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +$donut-width: 14px;
```suggestion
```
Is this unused?

2024-07-19 08:53 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +    margin: 0 10px;
Instead of pixel values, we should use the vanilla variables like `$spv--large` for a large vertical space or `$sph--large` for horizontal ones. More details in [the docs](https://vanillaframework.io/docs/settings/spacing-settings).

2024-07-19 08:53 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +}
Can this be an inline list from react components?

2024-07-19 08:53 UTC, edlerd commented on ui/src/pages/clusters/metrics/ClusterStatusGraph.tsx
> +          <div>
```suggestion
        <div>
```
I think we can remove this double nesting?

2024-07-19 08:53 UTC, edlerd commented on ui/src/pages/clusters/metrics/ClusterStatusGraph.tsx
> +              className="is-light p-side-navigation__icon"
```suggestion
```
This is not a side navigation and I think light is the default.

2024-07-19 08:53 UTC, edlerd commented on ui/src/pages/clusters/metrics/ClusterStatusGraph.tsx
> +              name={`status-succeeded-small`}
```suggestion
              name="status-succeeded-small"
```

2024-07-19 09:51 UTC, Kxiru commented on ui/src/sass/_cluster_graphs.scss
> +}
Nice idea, I have replaced this.

2024-07-19 10:29 UTC, edlerd requested changes
Some more ideas to reduce custom CSS.

The spacing in the header is a bit too big. Can you add `u-no-margin--bottom` to the "Add new cluster" button? That should improve the spacing.

2024-07-19 10:29 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +    margin: $sph--x-large;
```suggestion
    margin-left: $sph--x-large;
```

2024-07-19 10:29 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +    align-self: center;
```suggestion
```
Removing the top/bottom margin from the legend makes this obsolete.

2024-07-19 10:29 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +  }
```suggestion
```
I think we don't need this?

2024-07-19 10:29 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +  overflow: auto;
```suggestion
```
Why do we need this?

2024-07-19 10:29 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +}
```suggestion
```
This seems unused?

2024-07-19 11:16 UTC, Kxiru commented
Thanks @edlerd for your comments so far!

2024-07-19 11:32 UTC, edlerd requested changes
One tiny nitpick, also can you add this one class below to improve spacing? There is too much white space in the header.

> The spacing in the header is a bit too big. Can you add u-no-margin--bottom to the "Add new cluster" button? That should improve the spacing.

2024-07-19 11:32 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +}
```suggestion
}

```

2024-07-19 11:39 UTC, Kxiru commented
> One tiny nitpick, also can you add this one class below to improve spacing? There is too much white space in the header.
> 
> > The spacing in the header is a bit too big. Can you add u-no-margin--bottom to the "Add new cluster" button? That should improve the spacing.

Ah yes, I apologise, I missed that. All done!

2024-07-19 11:55 UTC, edlerd reviewed
Thanks for the fixes, nearly perfect now, just one more nitpick.

2024-07-19 11:55 UTC, edlerd commented on ui/src/pages/clusters/AddClusterButton.tsx
> +      className={"u-no-margin--bottom"}
```suggestion
      className="u-no-margin--bottom"
```

2024-07-19 12:04 UTC, mas-who commented on ui/src/components/DoughnutChart.tsx
> +const DoughnutChart = ({
let's use common convention in the code base. So `const DoughnutChart: FC<Props> = ({...})` instead of the current approach

2024-07-19 12:54 UTC, edlerd approved these changes
LGTM

2024-07-19 13:23 UTC, merged