tests: add e2e tests for backend endpoints [WD-13158]
canonical/microcloud-cluster-manager pull request #61
Opened 2024-07-19 15:41 UTC by mas-who

## Done
- Setup structure for backend e2e tests
- Add test helper functions for environment setup, cluster initialisation, test logging, creating http clients (unix and tls) and making requests
- Add e2e test for site join process
- Add e2e test for status updates

2024-07-19 15:41 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-61.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/6072)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-19 16:19 UTC, edlerd reviewed
I think we should
- either use a golang testing framework or
- have shell scripts that execute a series of command lines like `go run ./cmd/lxd-site-mgr --state-dir state/state_dir_1 external-site-join-token add foo12 --expiry=48h` followed by a `go run ./cmd/lxd-site-mgr --state-dir state/dir1 external-site-join-token list` and validate the output. Those can exit non-zero in case the output doesn't match.

2024-07-19 16:33 UTC, mas-who commented
> I think we should
> 
> * either use a golang testing framework or
> * have shell scripts that execute a series of command lines like `go run ./cmd/lxd-site-mgr --state-dir state/state_dir_1 external-site-join-token add foo12 --expiry=48h` followed by a `go run ./cmd/lxd-site-mgr --state-dir state/dir1 external-site-join-token list` and validate the output. Those can exit non-zero in case the output doesn't match.

The golang `httptest` framework won't work with the custom handlers we have to define in this project due to usage of microcluster.

The idea is not too far off from running a list of shell commands here, the reason why I chose to do the testing in go instead of just shell scripts is because I think setting up clients with proper certificates for the control listener tests etc would be much easier that way. Also we won't really need e2e tests for the management listener, since it would be covered by ui e2e tests.  Is there a particular benefit to do these tests using shell?

2024-07-22 21:06 UTC, mas-who commented
@edlerd I think it would be more organised to have another test suite for all cli commands. The e2e tests for the site join process and site status updates may cover some CLI commands but not all. It feels a bit better organised to comprehensively test the cli in a single test suite. Also happy to swap out the unix http requests in the current e2e tests to use cli though, let me know what you think.

2024-07-23 11:58 UTC, edlerd reviewed
This is looking very good, thanks for adding. I ended up having a lot of questions and suggestions below.

2024-07-23 11:58 UTC, edlerd commented on test/e2e/main_test.go
> +		t.Fatalf("Failed to testing initialize environment: %v", err)
```suggestion
		t.Fatalf("Failed to initialize test environment: %v", err)
```

2024-07-23 11:58 UTC, edlerd commented on test/e2e/main_test.go
> +	t.Log("Given the need to test the LXD site manager backend")
```suggestion
```

2024-07-23 11:58 UTC, edlerd commented on test/e2e/main_test.go
> +	}()
Shouldn't this be done in the helpers `NewEnv` or `Init` function?

2024-07-23 11:58 UTC, edlerd commented on test/helpers/env.go
> +	pids := bytes.Fields(awkOut.Bytes())
This is not a safe way to get the pids. There might be other processes matching and being killed below. Can we record the PID after calling `daemonCmd.Start();` instead to know which pids  to kill?

2024-07-23 11:58 UTC, edlerd commented on test/helpers/cert.go
> +func GetClusterCert(env *Environment) (*shared.CertInfo, error) {
Shouldn't this be a helper in env.go, so we can do `env.GetClustercert()`?

2024-07-23 11:58 UTC, edlerd commented on test/helpers/client.go
> +		DisableKeepAlives: true,
```suggestion
```
Why this?

2024-07-23 11:58 UTC, edlerd commented on test/helpers/client.go
> +		Proxy:             shared.ProxyFromEnvironment,
```suggestion
```
We don't need to support proxy here, should we?

2024-07-23 11:58 UTC, edlerd commented on test/helpers/client.go
> +	}
```suggestion
```
We don't need to support redirects, do we?

2024-07-23 11:58 UTC, edlerd commented on test/helpers/client.go
> +	}
Can't we rely on the default here?

2024-07-23 11:58 UTC, edlerd commented on test/helpers/cluster.go
> +	if err := daemonCmd.Start(); err != nil {
After this we should be able to read the pid of the background daemon.

2024-07-23 11:58 UTC, edlerd commented on test/e2e/site_join.go
> +			helpers.LogTestOutcome(t, condition, nil)
```suggestion
			helpers.LogTestOutcome(t, condition, err)
```
Can keep this simple?

2024-07-23 11:58 UTC, edlerd commented on test/e2e/site_join.go
> +			condition = "Should not be able to find the external site join token after receiving join request"
```suggestion
			condition = "Should have deleted the external site join token after receiving join request"
```

2024-07-23 11:58 UTC, edlerd commented on test/e2e/site_status.go
> +		}
This is duplicating from site join. Should we make one long scenario with join and status together instead, to avoid duplicating?

2024-07-23 12:23 UTC, mas-who commented on test/e2e/main_test.go
> +	}()
If we run cleanup in init, it will kill the daemon process before we hit the tests

2024-07-23 12:31 UTC, mas-who commented on test/helpers/env.go
> +	pids := bytes.Fields(awkOut.Bytes())
thanks for suggesting this. Yes it is possible after some reading. You can get the pid by `daemonCmd.Process.Pid`. We can introduce a `ProcessIDs` slice field for `Environment` and add all the pids to that slice during initialisation. Then in the cleanup function we can iterate those pids to terminate them.

2024-07-23 14:27 UTC, mas-who commented on test/helpers/cert.go
> +func GetClusterCert(env *Environment) (*shared.CertInfo, error) {
fair point :+1:

2024-07-23 14:32 UTC, mas-who commented on test/helpers/client.go
> +		DisableKeepAlives: true,
yeah no this is not required, removed.

2024-07-23 14:33 UTC, mas-who commented on test/helpers/client.go
> +		Proxy:             shared.ProxyFromEnvironment,
yes it's not required, we are not testing using any proxy so removed.

2024-07-23 14:33 UTC, mas-who commented on test/helpers/client.go
> +	}
removed.

2024-07-23 14:34 UTC, mas-who commented on test/helpers/client.go
> +	}
Yes indeed we can, removed.

2024-07-23 14:36 UTC, mas-who commented on test/helpers/cluster.go
> +	if err := daemonCmd.Start(); err != nil {
yes, now we have a `ProcessIDs` slice field for a instance of `Environment`. At this point we will add the pid to the slice and in `Environment.Cleanup` we will get the list of pids and terminate them.

2024-07-23 15:17 UTC, mas-who commented on test/e2e/site_status.go
> +		}
decided to just combine the test into a single file `site_control.go`. If we look at [kubernetes](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e_test.go) test folder structure, they also have a single entry point and seems they keep tests for different aspect of the system in separate folders. I don't think we are at that scale yet to make that kind of split though.

2024-07-23 21:05 UTC, edlerd reviewed
This looks good for the happy path. Shall we also add site join with an invalid hmac or expired cluster cert and status update with a not approved site or an invalid cluster cert?

2024-07-23 21:05 UTC, edlerd commented on test/e2e/e2e_test.go
> +	helpers.LogTestOutcome(t, "Initialize environment", nil)
```suggestion
	helpers.LogTestOutcome(t, "Initialize environment", err)
```

2024-07-23 21:05 UTC, edlerd commented on test/e2e/site_control.go
> +				err = fmt.Errorf("invalid site")
```suggestion
				err = fmt.Errorf("invalid site status")
```

2024-07-23 21:05 UTC, edlerd commented on test/helpers/cluster.go
> +	}
Should we rely on make here instead?

2024-07-24 07:43 UTC, mas-who commented on test/helpers/cluster.go
> +	}
great idea, done! :+1:

2024-07-24 08:20 UTC, edlerd commented on test/helpers/cluster.go
> +	}
I see the comments resolved / answered, did you maybe forget to push the changes or are you implementing more changes?

2024-07-24 08:25 UTC, mas-who commented on test/helpers/cluster.go
> +	}
yes I'm just adding the failure test cases before pushing. Resolved conversations to keep track of what I've done.

2024-07-24 09:52 UTC, mas-who commented
@edlerd I've added the failure cases as well for site join and site status update. The only case I didn't cover is for an expired client cert. The reason being that can not be done easily with the lxd shared package for certificates. To create a certificate that expires immediately, the logic is a bit involved and we could reuse some of the code from lxd but we'd have to copy them over into this project. This PR is already getting quite big, so I think we can always add that case at a later stage.

2024-07-24 10:22 UTC, edlerd commented on test/e2e/main_test.go
> +	}()
Ah right, because that function finishes early.

2024-07-24 10:44 UTC, edlerd requested changes

2024-07-24 10:44 UTC, edlerd commented on test/e2e/site_status.go
> +
```suggestion
```

2024-07-24 10:44 UTC, edlerd commented on test/e2e/site_join.go
> +			condition = "Should fail join request validation with invalid HMAC"
```suggestion
		{
			condition = "Should fail join request validation with invalid HMAC"

			token, _ = createSiteJoinToken(env, siteName, time.Time{})
			decodedToken, _ := base64.StdEncoding.DecodeString(token)
			json.Unmarshal(decodedToken, &tokenData)
```
As those prerequisites are covered by the happy path test, should we keep those failure tests focused on the failure case and avoid repeating the verbose checking of the pre-condition setup?

2024-07-24 10:44 UTC, edlerd commented on test/e2e/site_control.go
Shall we call this file `site_happy` and the other ones `site_fail_join` and `site_fail_status`?

2024-07-24 10:44 UTC, edlerd commented on test/helpers/env.go
> +	}
This is a indirect way of defining the root by finding the first one that has a go.mod file in it. Maybe use something like below instead? Or maybe there is a safer way?
```
    _, b, _, _ = runtime.Caller(0)
    basepath   = filepath.Dir(b)
```

2024-07-24 10:48 UTC, mas-who commented on test/e2e/site_status.go
> +
Why are we removing this?

2024-07-24 10:49 UTC, edlerd commented on test/e2e/site_status.go
> +
Sorry, forgot to comment. I think this is from the test above. This test is about another case, which is mentioned below.

2024-07-24 10:57 UTC, mas-who commented on test/e2e/site_join.go
> +			condition = "Should fail join request validation with invalid HMAC"
yeah good idea, will apply through out.

2024-07-24 10:59 UTC, mas-who commented on test/e2e/site_join.go
> +			condition = "Should fail join request validation with invalid HMAC"
I think we should still log the errors though.

2024-07-24 11:22 UTC, edlerd commented on test/e2e/site_join.go
> +			condition = "Should fail join request validation with invalid HMAC"
That is making the code so verbose. Is there a better way to keep the code slim?

2024-07-24 11:23 UTC, mas-who commented on test/e2e/site_status.go
> +
Aaah my bad I didn't look around the block of code.

2024-07-24 11:34 UTC, mas-who commented on test/e2e/site_join.go
> +			condition = "Should fail join request validation with invalid HMAC"
Since the token creation and decoding is a common sequence of events across all test cases. I've moved it into the helpers package as a token helper. So the error handling is mostly handled inside the helper function.

2024-07-24 11:36 UTC, mas-who commented on test/e2e/site_control.go
maybe `site_normal` instead of `site_happy`?

2024-07-24 11:38 UTC, edlerd commented on test/e2e/site_join.go
> +			condition = "Should fail join request validation with invalid HMAC"
nice, thanks.

2024-07-24 11:39 UTC, edlerd commented on test/e2e/site_control.go
Huh, what is normal these days :D Maybe `site_success`?

2024-07-24 11:52 UTC, mas-who commented on test/helpers/env.go
> +	}
I think it's safe to use the `go.mod` file since there can only be one for a go project, and we are expanding out from within the project. Problem with `runtime.Caller` is that it will return the directory from which the function is called, so it would still require some iterative logic to get back to the project root.

The current approach is a bit unsafe since we will hang the test program if `go.mod` file is missing for whatever reason in the project. I've added some logic so that if we reach the root of the file system, the program will exit with an error.

2024-07-24 11:53 UTC, mas-who commented on test/e2e/site_control.go
Haha yeah that sounds better :laughing:

2024-07-24 12:57 UTC, edlerd reviewed
This looks pretty good, I reviewed everything and have two questions left. In the site status fail case: I think we the prerequisites before sending the status request need a bit more refinement.

2024-07-24 12:57 UTC, edlerd commented on test/e2e/site_fail_status.go
> +			err = sendStatusUpdate(env, tokenData)
Don't we need to send the join request as well so the site is generated but not active?

2024-07-24 12:57 UTC, edlerd commented on test/e2e/site_fail_status.go
> +			err = sendStatusUpdateNoCert(env, tokenData)
I think we also need to send the join request and approve it so the site is active.

2024-07-24 17:11 UTC, mas-who commented on test/e2e/site_fail_status.go
> +			err = sendStatusUpdate(env, tokenData)
as discussed, I've added the join request steps to these test cases.

2024-07-24 17:11 UTC, mas-who commented on test/e2e/site_fail_status.go
> +			err = sendStatusUpdateNoCert(env, tokenData)
done.

2024-07-24 17:22 UTC, edlerd approved these changes
Good work, thanks for adding the tests and making them awesome.

2024-07-24 17:43 UTC, merged