feat: [WD-13372] Added inline notification system.
canonical/microcloud-cluster-manager pull request #62
Opened 2024-07-22 10:47 UTC by Kxiru

**Work done:**
- Added NotificationProvider and NotificationConsumer components.
- Implemented some initial notifications for approving and declining pending clusters, and creating new tokens.

Screenshots:
![image](https://github.com/user-attachments/assets/070669ba-65ef-4e82-aade-53117a6c3c4a)

![image](https://github.com/user-attachments/assets/39ccc891-a8f0-4ae6-b028-10804e175491)

![image](https://github.com/user-attachments/assets/10a0ce2f-1b8b-4cac-af0b-45a968480d84)

2024-07-22 10:47 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-62.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/6259)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-22 12:55 UTC, edlerd requested changes

2024-07-22 12:55 UTC, edlerd commented on ui/src/pages/clusters/ClusterList.tsx
> +        <NotificationRow />
I think this should appear below the tab links, not above them. The notifications relate to one tabs content, not to the generic charts above the tab selector.

2024-07-22 12:55 UTC, edlerd commented on ui/src/pages/clusters/CreateCluster.tsx
> +        notify.success(`Successfully created token ${tokenPayload.site_name}.`);
We should also print the token itself here, with a note, that it can never be accessed again and should be saved right away.

2024-07-22 12:55 UTC, edlerd commented on ui/src/pages/clusters/CreateCluster.tsx
> +        if (e.message === "Unable to create new Token.") {
I don't understand why we need this condition here. I think those lines should be removed.

2024-07-22 12:55 UTC, edlerd commented on ui/src/pages/clusters/CreateCluster.tsx
> +        notify.failure("Unable to create new Token.", e);
```suggestion
        notify.failure("Unable to create token.", e);
```
Better?

2024-07-22 12:55 UTC, edlerd commented on ui/src/pages/clusters/RevokeTokenButton.tsx
> +        notify.success(`Successfully deleted ${token.site_name} token.`);
```suggestion
        notify.success(`Successfully deleted token for cluster ${token.site_name}.`);
```

2024-07-22 12:55 UTC, edlerd commented on ui/src/pages/clusters/RevokeTokenButton.tsx
> +        if (e.message === "Unable to delete Token.") {
There shouldn't be a conditional here. We want to surface any error to the user.

2024-07-22 12:55 UTC, edlerd commented on ui/src/pages/clusters/RevokeTokenButton.tsx
> +        notify.success(`Successfully deleted ${token.site_name} token.`);
I think we should always use the wording "token for cluster :site-name", wdyt?

2024-07-22 13:01 UTC, Kxiru commented on ui/src/pages/clusters/RevokeTokenButton.tsx
> +        notify.success(`Successfully deleted ${token.site_name} token.`);
I suppose that does make sense, given the sitename is not the name of the token itself but instead of the cluster it is associated with.

2024-07-22 16:02 UTC, Kxiru commented on ui/src/pages/clusters/CreateCluster.tsx
> +        notify.success(`Successfully created token ${tokenPayload.site_name}.`);
![image](https://github.com/user-attachments/assets/90196a99-65c2-4258-abe5-909b03ddb0a7)

2024-07-22 16:39 UTC, edlerd requested changes

2024-07-22 16:39 UTC, edlerd commented on ui/src/pages/settings/SettingForm.tsx
> +        notify.success(`Successfully changed setting: ${configField}.`);
```suggestion
        notify.success(`Setting ${configField} updated.`);
```

2024-07-22 16:39 UTC, edlerd commented on ui/src/components/NavLink.tsx
> +    }
We shouldn't leak information about notification state into the nav components. Otherwise, we end up adding notify.clear to all our internal links as well. Better keep the responsibilities clear. We need to pass some props to the notification provider for this to work. See the other comment.

2024-07-22 16:39 UTC, edlerd commented on ui/src/Root.tsx
> +          <NotificationProvider>
```suggestion
          <NotificationProvider state={location.state} pathname={location.pathname}>
```
This paired with adding `const location = useLocation() as QueuedNotification;` above causes the notification to be cleared on navigation or whenever the pathname changes.

2024-07-22 16:39 UTC, edlerd commented on ui/src/pages/clusters/CreateCluster.tsx
> +        );
When implementing the other changes above, we're probably going to need a queued notification like `navigate("/ui...", notify.queue(notify.success(...)));` here, that is passed as a 2nd argument to navigate. Otherwise, this notification is in a race and might get cleared right away before being shown.

2024-07-23 07:24 UTC, mas-who commented on ui/src/components/NavLink.tsx
> +    }
This is my fault, I may have given some bad advice. @Kxiru please refer to [Root.tsx](https://github.com/canonical/lxd-ui/blob/main/src/Root.tsx) for reference to see how we pass location info to the `CombinedNotificationProvider` which internally has the `NotificationProvider` from react-components.

2024-07-23 07:31 UTC, mas-who commented on ui/src/api/tokens.ts
> +        resolve(data.metadata ?? []),
we shouldn't default output of this function to `[]` since the api response structure is different. In any case, if the backend ever returned a success response with no data, it means something has gone wrong. We would want to know this so letting the UI fail will inform on the issue and we can then resolve it later.

2024-07-23 07:54 UTC, mas-who commented
> **Work done:**
> 
> * Added NotificationProvider and NotificationConsumer components.
> * Implemented some initial notifications for approving and declining pending clusters, and creating new tokens.
> 
> Screenshots: ![image](https://private-user-images.githubusercontent.com/58699506/350936837-070669ba-65ef-4e82-aade-53117a6c3c4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjEzNDYsIm5iZiI6MTcyMTcyMTA0NiwicGF0aCI6Ii81ODY5OTUwNi8zNTA5MzY4MzctMDcwNjY5YmEtNjVlZi00ZTgyLWFhZGUtNTMxMTdhNmMzYzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NmJjY2FmZDFkMzQ3MTllNzdmZDkzZjMzY2Y3YjFjYzBjOWI4ZmMzOTRkNGJiN2FmYTczZjc0N2Q0ZGFkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VkF85yA73p79s4Yj83bWYKYSxj5-bD_Z51QIbqgvOdM)
> 
> ![image](https://private-user-images.githubusercontent.com/58699506/350936925-39ccc891-a8f0-4ae6-b028-10804e175491.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjEzNDYsIm5iZiI6MTcyMTcyMTA0NiwicGF0aCI6Ii81ODY5OTUwNi8zNTA5MzY5MjUtMzljY2M4OTEtYThmMC00YWU2LWIwMjgtMTA4MDRlMTc1NDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZTI5NjZjMzI4YWY5NzIxY2Q5Y2QxZGE4ZTI2ZjI3YTBlODJmZjE3MWVkYWVlOTZjNDM4ZWUyMGIzZjcwMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ptbiGxhwgD-_IlfIgqYgFlH7yPO6nSGIx9eDYnZTick)
> 
> ![image](https://private-user-images.githubusercontent.com/58699506/351034264-10a0ce2f-1b8b-4cac-af0b-45a968480d84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjEzNDYsIm5iZiI6MTcyMTcyMTA0NiwicGF0aCI6Ii81ODY5OTUwNi8zNTEwMzQyNjQtMTBhMGNlMmYtMWI4Yi00Y2FjLWFmMGItNDVhOTY4NDgwZDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYjdiM2JiYTA4ZGQyYmIxODFmNGI0NDdjNDI5YWM3MTRjYjhlNWRhMTI2ODI0OGE4YzNjZmZkNjYwYTZiZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tN9LeIVKvHluPi4QzwvM-r8fSYZq-4AMtmNNdhAspP0)

I think for the token success message, the `p` element that contains the token has a `max-width` of `40rem`, which is the default from vanilla. It looks a bit weird in this case, I think we should override it so that the element spans 100% of the container width. wdyt @Kxiru @edlerd ?

2024-07-23 08:52 UTC, edlerd commented
> I think for the token success message, the `p` element that contains the token has a `max-width` of `40rem`, which is the default from vanilla. It looks a bit weird in this case, I think we should override it so that the element spans 100% of the container width. wdyt @Kxiru @edlerd ?

I think p is the wrong element, we should use [code](https://vanillaframework.io/docs/base/code) instead. Then we won't need a CSS override any more, and I think it will look better automatically.

2024-07-23 12:22 UTC, Kxiru commented on ui/src/pages/clusters/CreateCluster.tsx
> +        );
When implementing this approach, the page does not navigate back from the cluster creation page to the token list page, although it does display the notification. Any idea why this could be?

2024-07-23 13:29 UTC, edlerd commented on ui/src/pages/clusters/CreateCluster.tsx
> +        );
```suggestion
        navigate(
          "/ui/sites/tokens",
          notify.queue(
            notify.success(
              response.token,
              "The token has been created and will be displayed only once. Please save it now:",
            ),
          ),
        );
```
We can't use any JSX in the queued notifications. The content must be text only. With this it works, but we need some extra scss to make the token break into multiple lines:

```
p-notification__message {
    word-break: break-word;
}
```
I think we can just add this to our scss and suggest it as a fix in vanilla as well.

2024-07-23 13:39 UTC, Kxiru commented on ui/src/pages/clusters/CreateCluster.tsx
> +        );
I'll reach out to the Vanilla team now :). Thanks for your help!

2024-07-23 13:50 UTC, edlerd reviewed
QA & code LGTM.

2024-07-23 13:58 UTC, edlerd approved these changes

2024-07-23 14:15 UTC, merged