ui: added disk and memory distribution graphs for cluster list [WD-13150]
canonical/microcloud-cluster-manager pull request #63
Opened 2024-07-23 10:30 UTC by mas-who

## Done
 - created `HorizontalDistGraph` component for displaying numerical data distributions along the y-axis
 - use `HorizontalDistGraph` to display disk and memory usage for clusters
 - added styling to make mobile view with the graphs list a bit easier on the eyes

2024-07-23 10:30 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-63.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/6465)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-23 14:04 UTC, Kxiru reviewed
Looks great, in my opinion! Just a small idea, below.

2024-07-23 14:04 UTC, Kxiru commented on ui/src/components/HorizontalDistGraph.tsx
> +      <p className="u-no-margin u-no-padding">{title}</p>
Is it worth making the title of the graph have the same styling as the title of the Cluster status graph for continuity purposes? Let me know your thoughts.
For reference, the styling of the status graph title is as follows:
```className="u-no-margin p-heading--5"```

Or perhaps that title should change to yours? In any case, I think the consistency would be useful.

2024-07-24 13:40 UTC, edlerd requested changes
This looks very good visually and so slim for the code as well.

Some small naming and minor structural comments below.

2024-07-24 13:40 UTC, edlerd commented on ui/src/components/HorizontalDistGraph.tsx
> +const HorizontalDistGraph: FC<Props> = ({
Maybe better `PercentileChart`?

2024-07-24 13:40 UTC, edlerd commented on ui/src/sass/styles.scss
Why reorder the imports here? Makes it hard to see the actual changes

2024-07-24 13:40 UTC, edlerd commented on ui/src/sass/_cluster_graphs.scss
> +    width: fit-content;
```suggestion
  .cluster-status {
    display: flex;
```
I think those are not needed?

2024-07-24 13:40 UTC, edlerd commented on ui/src/pages/clusters/metrics/ClusterMemoryGraph.tsx
> +const GRAPH_COLOR = "#B04000";
I think we shouldn't have those in tsx. We define classes in `_meter.scss` with the colours for disk and memory, maybe make those reusable?

2024-07-24 13:40 UTC, edlerd commented on ui/src/components/HorizontalDistGraph.tsx
> +  const barWidth = height / data.length;
Should this be bar height as it is horizontal?

2024-07-24 13:42 UTC, edlerd commented
I think the headings and the lower end of the graphs should be aligned:

![image](https://github.com/user-attachments/assets/84409a8f-5ff8-44b2-9f3a-5c6dc8e34d97)

2024-07-24 18:30 UTC, mas-who commented on ui/src/components/HorizontalDistGraph.tsx
> +  const barWidth = height / data.length;
In my head width and height is now inverted as the chart is horizontal, so `barWidth` makes sense to me since we assign it to the `height` property of the `rect` element :thinking:

2024-07-24 18:35 UTC, mas-who commented on ui/src/sass/_cluster_graphs.scss
> +    width: fit-content;
yup not needed

2024-07-24 18:39 UTC, mas-who commented on ui/src/sass/styles.scss
I found there was an error that if `./breakpoints` was imported after other partials, it results in a build error. That was the primary reason for the re-order, but instead of just moving `breakpoints` higher, I decided to align the importing structure with lxd-ui

2024-07-24 18:43 UTC, edlerd commented on ui/src/sass/styles.scss
Then can we have a new line before the other file imports and sort them alphabetically?

2024-07-24 18:57 UTC, mas-who commented on ui/src/sass/styles.scss
I had them sorted in the wrong order previously I see :sweat:

2024-07-24 19:28 UTC, mas-who commented
> I think the headings and the lower end of the graphs should be aligned:
> 
> ![image](https://private-user-images.githubusercontent.com/1155472/351737802-84409a8f-5ff8-44b2-9f3a-5c6dc8e34d97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDkyMDksIm5iZiI6MTcyMTg0ODkwOSwicGF0aCI6Ii8xMTU1NDcyLzM1MTczNzgwMi04NDQwOWE4Zi01ZmY4LTQ0YjItOWYzYS01YzZkYzhlMzRkOTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMTkyMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc2YWNmNDkxNWYyYzBhZDU2MjEzZGZmOGUzOTMzZmZmYzI0YjMxNWVlNWQ2ZTkzOWEwYzY5OGNmMDFiNTQzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0Oy8RqUFffYdtRGdDyU3xIgHqOetKWhpR4qyvt3PBDs)

I think it's aligned now, but I may also be seeing things since it's late.

![Screenshot from 2024-07-24 21-27-49](https://github.com/user-attachments/assets/0b1548bc-fbc5-45d9-acad-547c6e099d95)

2024-07-24 19:45 UTC, edlerd approved these changes
LGTM, thanks for the adjustments.

For checking alignment I can recommend page ruler for [chrome](https://chromewebstore.google.com/detail/page-ruler/jcbmcnpepaddcedmjdcmhbekjhbfnlff?hl=en) or [firefox](https://addons.mozilla.org/en-US/firefox/addon/page-ruler/).

2024-07-25 07:56 UTC, merged