chore: rename site manager to cluster manager [WD-13647]
canonical/microcloud-cluster-manager pull request #67
Opened 2024-07-26 07:49 UTC by mas-who

## Done
 - all references to "site" are now removed and replaced with "remote-cluster"
 - updated api endpoints
 - updated cli commands
 - updated all variables and file names
 - updated database schema.

2024-07-26 07:49 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-site-manager-67.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/7273)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-29 16:28 UTC, edlerd requested changes
Thanks for the update!

Did some spot checking and found a couple of open issues below.

2024-07-29 16:28 UTC, edlerd commented on cmd/lxd-cluster-mgr/main_init.go
> +		return fmt.Errorf("Unable to configure LXD cluster manager cluster: %w", err)
```suggestion
		return fmt.Errorf("Unable to configure cluster: %w", err)
```

2024-07-29 16:28 UTC, edlerd commented on cmd/lxd-cluster-mgr/main_init.go
> +		Short: "Initialize the network endpoint and create or join a internal new cluster",
```suggestion
		Short: "Initialize the network endpoint and create new cluster or join an existing one",
```

2024-07-29 16:28 UTC, edlerd commented on cmd/lxd-cluster-mgr/main_init.go
> +		return fmt.Errorf("Unable to configure LXD cluster manager cluster: %w", err)
Too much cluster in the help text otherwise.

2024-07-29 16:28 UTC, edlerd commented on cmd/lxd-cluster-mgr/remote_cluster_join_tokens.go
> +		Short: "Add a new external join token for a LXD cluster.",
```suggestion
		Short: "Add a new remote join token for a LXD cluster.",
```

2024-07-29 16:28 UTC, edlerd commented on cmd/lxd-cluster-mgr/remote_cluster_join_tokens.go
> +			Will created an external cluster join token for a LXD cluster.
```suggestion
			Will created an remote cluster join token for a LXD cluster.
```

2024-07-29 16:28 UTC, edlerd commented on cmd/lxd-cluster-mgr/remote_cluster_join_tokens.go
> +		Short: "Revoke the external cluster join token with the given LXD cluster name.",
```suggestion
		Short: "Revoke the remote cluster join token with the given name.",
```

2024-07-29 16:28 UTC, edlerd commented on cmd/lxd-cluster-mgr/remote_cluster_join_tokens.go
> +			Will render the specific external cluster join token invalid.
```suggestion
			Will render the specific remote cluster join token invalid.
```

2024-07-29 16:28 UTC, edlerd commented on internal/api/remoet_cluster_control.go
Typo in file name

2024-07-29 16:28 UTC, edlerd commented on internal/api/types/remtoe_cluster_management.go
typo

2024-07-29 16:28 UTC, edlerd commented on internal/database/remote_cluster_details.go
> +	CPULoad15           string `db:"sql=remote_cluster_details.cpu_load_15"`
Why are those three special and have a db/sql string?

2024-07-29 16:28 UTC, edlerd commented on ui/src/components/Logo.tsx
> +      <div className="logo-text p-heading--4">LXD Cluster Manager</div>
This doesn't work, as it spills into a 2nd line. We have to stay in one line. Some ideas:
- Cluster Manager
- LXD Manager
- LXD Cluster Mgr
- widen the navigation to 18rem width.

We can keep the long name in title and login screens, but need to find a solution for the navigation. I don't have a strong preference. Maybe the 1st option above?

2024-07-29 16:41 UTC, mas-who commented on cmd/lxd-cluster-mgr/main_init.go
> +		return fmt.Errorf("Unable to configure LXD cluster manager cluster: %w", err)
also adjusted another comment that has the same structure.

2024-07-29 16:50 UTC, mas-who commented on internal/database/remote_cluster_details.go
> +	CPULoad15           string `db:"sql=remote_cluster_details.cpu_load_15"`
A struct field in the form of `CPULoad1` would be transformed by `lxd-generate` to `cpu_load1` in the database, this doesn't work well with a json struct tag. Here we specifically map the fields to db column names.

2024-07-29 17:29 UTC, mas-who commented on ui/src/components/Logo.tsx
> +      <div className="logo-text p-heading--4">LXD Cluster Manager</div>
I think "LXD Manager" is probably the best one here

2024-07-30 08:01 UTC, edlerd requested changes
Mostly good to go. One more idea to improve copy, and I'd keep the full name in the title as it is very prominently visible to the user.

2024-07-30 08:01 UTC, edlerd commented on internal/database/manager_configs.go
> +// ManagerConfig configurations for the entire manager cluster.
```suggestion
// ManagerConfig configurations for the entire cluster.
```

2024-07-30 08:01 UTC, edlerd commented on ui/index.html
> +    <title>LXD Manager</title>
We have enough space here for the full name
```suggestion
    <title>LXD Cluster Manager</title>
```

2024-07-30 08:01 UTC, edlerd commented on ui/tests/cluster-list.spec.ts
> +  expect(await page.title()).toBe("LXD Manager");
```suggestion
  expect(await page.title()).toBe("LXD Cluster Manager");
```

2024-07-30 08:02 UTC, edlerd requested changes

2024-07-30 08:02 UTC, edlerd commented on ui/src/pages/Login.tsx
> +      <LoginPageLayout title="Login to LXD cluster manager">
```suggestion
      <LoginPageLayout title="Login to LXD Cluster Manager">
```
We should use the same capitalization everywhere.

2024-07-30 08:10 UTC, mas-who commented on ui/src/pages/Login.tsx
> +      <LoginPageLayout title="Login to LXD cluster manager">
I've also updated the CLI help texts to use the same capitalization

2024-07-30 08:26 UTC, edlerd submitted a review, later dismissed
LGTM, thanks for this massive change!

Just one nitpick below. Maybe check if we have other occasions where we should avoid "LXD Cluster Manager clusters" or "Cluster Manager clusters". I think we should avoid the product name there.

2024-07-30 08:26 UTC, edlerd commented on entrypoint
> +# initialise the Cluster Manager cluster
```suggestion
# initialise the cluster
```
Lets avoid too much cluster?

2024-07-30 08:36 UTC, mas-who commented on entrypoint
> +# initialise the Cluster Manager cluster
good catch, I did a global search for "manager cluster" and "cluster cluster" (just in case). The only entry was found in the above file.

2024-07-30 08:46 UTC, edlerd approved these changes

2024-07-30 08:48 UTC, merged