feat: [WD-13078] Added search and filter for cluster list
canonical/microcloud-cluster-manager pull request #83
Opened 2024-08-06 18:26 UTC by Kxiru

Work done:
- Implemeneted Custom Layout
- Implemented Pageheader component
- Implemented ClusterSearchFilter component alongside all relevant types
- Added ClusterSearchFilter to ClusterList
- Added Search Logic and Filter Logic
- Added scss styling for the page header.
- Minor other scss changes for consistency

Notes:
- Amended generate_cluster script so that it generates null (0) values for some of the clusters, for testing purposes. Whilst you can filter by statuses, this was not initially available in the UI. To counter this, I amended the generate_cluster script such that there became a way for "Running" instance statuses and "Online" Node statuses to be 0. Now, we can filter by those two statuses (for testing).

![image](https://github.com/user-attachments/assets/38c6bae3-b115-4f60-96a9-373607896453)

![image](https://github.com/user-attachments/assets/33baa6c3-eac5-4c0e-915c-969e17ba396d)

![image](https://github.com/user-attachments/assets/9d89cc3d-8f37-4a0b-b35c-e7369e0ecea7)
- ^ Filter by Memory where Memory is >90%.
- Note the change in URL params.

![image](https://github.com/user-attachments/assets/a69545c5-e850-4916-90d0-986adca873c5)
- ^ Filter by Memory where Memory is >90% and Node status is online.

2024-08-06 18:26 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://lxd-cluster-manager-83.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/9235)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-08-07 08:03 UTC, mas-who commented
This looks good! Having filtering makes it much easier to navigate the cluster list :+1: 

Have some QA comments so far:

1. The search and filter should either be hidden or disabled if we are on the "Pending" or "Tokens" tab. Although we don't need to clear the filters.
2. When I filtered by instance status, I expect the number of clusters shown to be the same as unfiltered cluster list if I selected all possible instance statuses. But it seems like that's not the case, see below screenshot (the total number of clusters is 95 instead of 100). Same goes for the other filter categories except the memory and disk ones.
![Screenshot from 2024-08-07 09-41-45](https://github.com/user-attachments/assets/6e872958-f296-4bdb-8735-e7657095e68c)
3. The graphs above should also be adjusted according to the filters. This will require implementing the same filtering logic inside the active clusters component as well as the graph components. I'd suggest create a utils function for this.
4. One more case we should test with the data. What happens if no clusters should be displayed due to the filters? You can adjust the `generate_clusters.sh` script for this by removing all instance statuses except for one as an example, just don't check in these changes.

2024-08-07 09:09 UTC, mas-who requested changes
Some feedback on code.

2024-08-07 09:09 UTC, mas-who commented on ui/src/components/ClusterSearchFilter.tsx
> +import { FC, memo } from "react";
this component should be in `/pages/clusters`.

2024-08-07 09:09 UTC, mas-who commented on ui/src/components/ClusterSearchFilter.tsx
> +export const INSTANCE_STATUS = "instanceStatus";
prefer snake casing for params in url e.g `instance-status`

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +  instance_statuses: ClusterInstanceStatuses[];
camel case for these field names e.g. `instanceStatuses`

2024-08-07 09:09 UTC, mas-who commented on ui/src/types/cluster.d.ts
> +export type ClusterInstanceStatuses =
The type name should be singular and not plural since it's not a list

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +export const instanceStatuses: string[] = [
we can use the the new type `ClusterInstanceStatus`

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +export const nodeStatuses: string[] = [
we can use the the new type `ClusterNodeStatus`

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +export const usagePercentiles: string[] = [">50%", ">75%", ">80%", ">90%"];
If the list can only have distinct values, then we shouldn't assign the `string[]` type to it. We should just let typescript to implicitly assign the type in this case.

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +export const enrichUsages = (percentiles: string[]): number[] => {
type for the `percentiles` input could be strict here instead of `string[]`? Also I find the name of the function a bit confusing, I think what this function is doing is converting the percentile filters from string to numeric format. Perhaps `toNumericUsagePercentiles` is a bit clearer?

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +  return filterStatuses.every((status) =>
applying `every` here means we have an `AND` condition for every status filter. I think the filters should behave as `OR` conditions within a single filter category and `AND` conditions across filter categories (same in lxd UI). This explains my QA comment where not all clusters are shown when selecting every status in the instance status filter category.

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +    matchingStatuses.some(
here instead of iterating every `matchingStatuses` for every `filterStatuses`. You can convert `matchingStatuses` to a object `{ [status: string]: number }` with keys being the status and values being the associated count. Then you can do something like the following:
```
filterStatuses.some((status) => filterStatusCountLookup[status] >= 1)
```

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +export const hasAllMatchingUsageClasses = (
maybe `hasAllUsagePercentileBands`?

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +    enrichedUsages.push(50);
we could use the normalised numerical values for the percentiles e,g. 0.5, 0.75 etc. We wouldn't have to apply a multiplier when comparing to these filters later

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +  usageClasses: number[],
maybe `usagePercentileBands`?

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +  const usagePercentage = Math.floor((use / total) * 100);
no need to do this calculation if the filters are normalised. Related to a previous comment.

2024-08-07 09:09 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +  console.log(usagePercentage);
remove console.log

2024-08-07 09:09 UTC, mas-who commented on ui/src/components/CustomLayout.tsx
> +    <main className={classnames("l-main", mainClassName)}>
Looking at the component, I think we can just use the `title` prop of `BaseLayout` to setup `PageHeader` instead of having the `CustomLayout` component.

2024-08-07 09:09 UTC, mas-who commented on ui/src/pages/clusters/ClusterList.tsx
> +  const { data: clusters = [], isLoading } = useQuery({
why did we move this query here from `ClusterListActive`?

2024-08-07 09:09 UTC, mas-who commented on ui/src/pages/clusters/ClusterList.tsx
> +    instance_statuses: searchParams.getAll(
field names and url params need to be adjusted here based on changes in `clusterFilter.tsx`.

2024-08-07 09:09 UTC, mas-who commented on ui/src/pages/clusters/ClusterList.tsx
> +      //Search by Clusters with more than one instance in a particular status
```suggestion
      //Search by Clusters with more than one instance having a particular status
```

2024-08-07 09:09 UTC, mas-who commented on ui/src/pages/clusters/ClusterList.tsx
> +      //Search by Clusters with more than one node in a particular status
```suggestion
      //Search by Clusters with more than one node having a particular status
```

2024-08-07 09:09 UTC, mas-who commented on ui/src/pages/clusters/ClusterList.tsx
> +    <CustomLayout
see if you can use the `BaseLayout` component `PageHeader` passed to the `title` prop?

2024-08-07 09:09 UTC, mas-who commented on ui/src/pages/clusters/ClusterListActive.tsx
> -  const { data: clusters = [], isLoading } = useQuery({
We should keep the query in this component

2024-08-07 14:03 UTC, Kxiru commented on ui/src/util/clusterFilter.tsx
> +export const enrichUsages = (percentiles: string[]): number[] => {
Originally the percentiles input was strictly typed but in the way this is done in LXD-UI, a string array becomes populated with the original types as well as the enriched types, which are also strings. In this case, as the enriched types are NOT strings, I did not feel it appropriate to create an interface/type that featured two different data types. See [here](https://github.com/Kxiru/lxd-ui/blob/dd5e43ea556cd06636fa3de07ddf33b0ec99a9e7/src/util/instanceFilter.tsx#L19) to view how this is incorporated in LXD-UI.

2024-08-07 14:10 UTC, Kxiru commented on ui/src/components/CustomLayout.tsx
> +    <main className={classnames("l-main", mainClassName)}>
![image](https://github.com/user-attachments/assets/5fff249a-32e2-4595-ab8d-6d1566372e15)

Custom Layout also comes with relevant parent styling.

2024-08-07 14:12 UTC, Kxiru commented on ui/src/pages/clusters/ClusterList.tsx
> +  const { data: clusters = [], isLoading } = useQuery({
It was moved because clusters needs to initialise the ClusterActiveList as well as the filteredClusters, which is then passed through. ClusterListActive does not need to recall this api in my understanding. ClusterListActive only reflects the filtered clusters, or all active clusters (no filter applied).

2024-08-07 14:15 UTC, Kxiru commented on ui/src/pages/clusters/ClusterList.tsx
> +    <CustomLayout
Please see above. Also here is what it looks like without the aforementioned styling.
![image](https://github.com/user-attachments/assets/de14ffba-84ff-47d7-a298-f78f751cfb8c)

But it's not impossible! Let me know how you would like me to proceed.

2024-08-07 14:16 UTC, Kxiru commented on ui/src/pages/clusters/ClusterListActive.tsx
> -  const { data: clusters = [], isLoading } = useQuery({
Could you explain why?

2024-08-07 14:26 UTC, Kxiru commented
> This looks good! Having filtering makes it much easier to navigate the cluster list 👍
> 
> Have some QA comments so far:
> 
> 1. The search and filter should either be hidden or disabled if we are on the "Pending" or "Tokens" tab. Although we don't need to clear the filters.
> 2. When I filtered by instance status, I expect the number of clusters shown to be the same as unfiltered cluster list if I selected all possible instance statuses. But it seems like that's not the case, see below screenshot (the total number of clusters is 95 instead of 100). Same goes for the other filter categories except the memory and disk ones.
>    ![Screenshot from 2024-08-07 09-41-45](https://private-user-images.githubusercontent.com/151511568/355722213-6e872958-f296-4bdb-8735-e7657095e68c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDA2NTcsIm5iZiI6MTcyMzA0MDM1NywicGF0aCI6Ii8xNTE1MTE1NjgvMzU1NzIyMjEzLTZlODcyOTU4LWYyOTYtNGJkYi04NzM1LWU3NjU3MDk1ZTY4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxNDE5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzczYTFlOTc4ZGZlMWUzZmU1YTdkNTA3OWMwNTJhYjg2YThkNGQ2MmJlNjdjY2ZhZDVmMDMzMDgyOWFmNjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dG2F1Hn25wpYIe7_TfFg7KKpabVGgVax3_crhNIJFXU)
> 3. The graphs above should also be adjusted according to the filters. This will require implementing the same filtering logic inside the active clusters component as well as the graph components. I'd suggest create a utils function for this.
> 4. One more case we should test with the data. What happens if no clusters should be displayed due to the filters? You can adjust the `generate_clusters.sh` script for this by removing all instance statuses except for one as an example, just don't check in these changes.

RE:
1) Yes, this is correct, thank you.
2) The total clusters changing to 95 is correct. As given my changes in generateClusters sh, 5 instances will be generated that have no running instances. For nodes, this goes from 100 to 50. Unless I have misunderstood, please could you clarify?
3) This can be done simply by passing the filtered clusters through to the graph components as has been done for ClusterListActive (and minor amendments to the component props). Could you advise why you think separate utils would be necessary for this?
4) I have seen and tested this. In the table, the string "No clusters found matching this search." is returned (From ClusterListActive)

2024-08-07 14:28 UTC, Kxiru commented on ui/src/util/clusterFilter.tsx
> +  return filterStatuses.every((status) =>
I think I understand what you are saying, however the AND logic between filter categories takes place in the filteredClusters const, whilst the OR logic within a single filter category is one in the hasAllMatchingStatuses function, already.

2024-08-07 15:36 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +  return filterStatuses.every((status) =>
as discussed, please would you reach out to @piperdeck to see if AND logic makes sense within the same filter category

2024-08-07 15:37 UTC, mas-who commented on ui/src/components/CustomLayout.tsx
> +    <main className={classnames("l-main", mainClassName)}>
aren't those the same props in `BaseLayout`?

2024-08-07 15:38 UTC, mas-who commented on ui/src/pages/clusters/ClusterList.tsx
> +  const { data: clusters = [], isLoading } = useQuery({
as discussed, let's have the data in the `ClusterList` parent component, so we can reused the filtered data in children components such as the graphs

2024-08-07 15:38 UTC, mas-who commented on ui/src/pages/clusters/ClusterList.tsx
> +    <CustomLayout
let's get the filtered clusters as prop input to the graphs as discussed

2024-08-07 15:39 UTC, mas-who commented on ui/src/pages/clusters/ClusterListActive.tsx
> -  const { data: clusters = [], isLoading } = useQuery({
no longer relevant

2024-08-07 19:14 UTC, Kxiru commented on ui/src/components/CustomLayout.tsx
> +    <main className={classnames("l-main", mainClassName)}>
It should as they are built into Panel, right? Here is BaseLayout.
![image](https://github.com/user-attachments/assets/7d890d8a-d587-4c5a-a04c-bc3e990ff8b5)

2024-08-08 08:36 UTC, mas-who commented on ui/src/components/CustomLayout.tsx
> +    <main className={classnames("l-main", mainClassName)}>
I see what you are saying, we can't apply custom style to the `p-panel__header` element. Alright then let's keep the `CustomLayout` component and just use `AppMain` for the `l-main` element.

2024-08-08 08:41 UTC, mas-who reviewed
Almost there, some minor comments. Also just need to align on the filter logic for instance and node statuses, that should be a quick one, see if you can follow up with @piperdeck sometime today.

2024-08-08 08:41 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +export const instanceStatuses: string[] = [
this is still `string[]`?

2024-08-08 08:41 UTC, mas-who commented on ui/src/util/clusterFilter.tsx
> +export const nodeStatuses: string[] = [
still `string[]`?

2024-08-08 15:20 UTC, mas-who commented on ui/src/components/CustomLayout.tsx
> +    <AppMain>
we should still get `mainClassName` here similar to `BaseLayout`

2024-08-08 16:05 UTC, mas-who approved these changes

2024-08-08 16:05 UTC, mas-who commented
LGTM :+1:

2024-08-08 17:39 UTC, merged